// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr/v1/micro/usermgr.proto

package usermgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserStatus int32

const (
	UserStatus_CONFIRMING  UserStatus = 0
	UserStatus_CONFIRMED   UserStatus = 1
	UserStatus_DEACTIVATED UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "CONFIRMING",
	1: "CONFIRMED",
	2: "DEACTIVATED",
}

var UserStatus_value = map[string]int32{
	"CONFIRMING":  0,
	"CONFIRMED":   1,
	"DEACTIVATED": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{0}
}

type SearchDepositRequest struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchDepositRequest) Reset()         { *m = SearchDepositRequest{} }
func (m *SearchDepositRequest) String() string { return proto.CompactTextString(m) }
func (*SearchDepositRequest) ProtoMessage()    {}
func (*SearchDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{0}
}

func (m *SearchDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchDepositRequest.Unmarshal(m, b)
}
func (m *SearchDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchDepositRequest.Marshal(b, m, deterministic)
}
func (m *SearchDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchDepositRequest.Merge(m, src)
}
func (m *SearchDepositRequest) XXX_Size() int {
	return xxx_messageInfo_SearchDepositRequest.Size(m)
}
func (m *SearchDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchDepositRequest proto.InternalMessageInfo

func (m *SearchDepositRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SearchDepositRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type GenerateAddressRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Propose              string   `protobuf:"bytes,2,opt,name=propose,proto3" json:"propose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressRequest) Reset()         { *m = GenerateAddressRequest{} }
func (m *GenerateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressRequest) ProtoMessage()    {}
func (*GenerateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{1}
}

func (m *GenerateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressRequest.Unmarshal(m, b)
}
func (m *GenerateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressRequest.Marshal(b, m, deterministic)
}
func (m *GenerateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressRequest.Merge(m, src)
}
func (m *GenerateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressRequest.Size(m)
}
func (m *GenerateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressRequest proto.InternalMessageInfo

func (m *GenerateAddressRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GenerateAddressRequest) GetPropose() string {
	if m != nil {
		return m.Propose
	}
	return ""
}

type GenerateAddressResponse struct {
	Typeaddress          string   `protobuf:"bytes,1,opt,name=typeaddress,proto3" json:"typeaddress,omitempty"`
	Purposeaddress       string   `protobuf:"bytes,2,opt,name=purposeaddress,proto3" json:"purposeaddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateAddressResponse) Reset()         { *m = GenerateAddressResponse{} }
func (m *GenerateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateAddressResponse) ProtoMessage()    {}
func (*GenerateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{2}
}

func (m *GenerateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateAddressResponse.Unmarshal(m, b)
}
func (m *GenerateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateAddressResponse.Marshal(b, m, deterministic)
}
func (m *GenerateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateAddressResponse.Merge(m, src)
}
func (m *GenerateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateAddressResponse.Size(m)
}
func (m *GenerateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateAddressResponse proto.InternalMessageInfo

func (m *GenerateAddressResponse) GetTypeaddress() string {
	if m != nil {
		return m.Typeaddress
	}
	return ""
}

func (m *GenerateAddressResponse) GetPurposeaddress() string {
	if m != nil {
		return m.Purposeaddress
	}
	return ""
}

type GetERCDepositResponse struct {
	Deposits             []*common.Deposit `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetERCDepositResponse) Reset()         { *m = GetERCDepositResponse{} }
func (m *GetERCDepositResponse) String() string { return proto.CompactTextString(m) }
func (*GetERCDepositResponse) ProtoMessage()    {}
func (*GetERCDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{3}
}

func (m *GetERCDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetERCDepositResponse.Unmarshal(m, b)
}
func (m *GetERCDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetERCDepositResponse.Marshal(b, m, deterministic)
}
func (m *GetERCDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetERCDepositResponse.Merge(m, src)
}
func (m *GetERCDepositResponse) XXX_Size() int {
	return xxx_messageInfo_GetERCDepositResponse.Size(m)
}
func (m *GetERCDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetERCDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetERCDepositResponse proto.InternalMessageInfo

func (m *GetERCDepositResponse) GetDeposits() []*common.Deposit {
	if m != nil {
		return m.Deposits
	}
	return nil
}

type User struct {
	// uuid
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// email user's email, unique.
	Email                string          `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status               UserStatus      `protobuf:"varint,3,opt,name=status,proto3,enum=usermgr.UserStatus" json:"status,omitempty"`
	Attributes           *UserAttributes `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_CONFIRMING
}

func (m *User) GetAttributes() *UserAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type UserAttribute struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*UserAttribute_IntValue
	//	*UserAttribute_DoubleValue
	//	*UserAttribute_StringValue
	//	*UserAttribute_BoolValue
	Value                isUserAttribute_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserAttribute) Reset()         { *m = UserAttribute{} }
func (m *UserAttribute) String() string { return proto.CompactTextString(m) }
func (*UserAttribute) ProtoMessage()    {}
func (*UserAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{5}
}

func (m *UserAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAttribute.Unmarshal(m, b)
}
func (m *UserAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAttribute.Marshal(b, m, deterministic)
}
func (m *UserAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAttribute.Merge(m, src)
}
func (m *UserAttribute) XXX_Size() int {
	return xxx_messageInfo_UserAttribute.Size(m)
}
func (m *UserAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_UserAttribute proto.InternalMessageInfo

func (m *UserAttribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type isUserAttribute_Value interface {
	isUserAttribute_Value()
}

type UserAttribute_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type UserAttribute_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type UserAttribute_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type UserAttribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*UserAttribute_IntValue) isUserAttribute_Value() {}

func (*UserAttribute_DoubleValue) isUserAttribute_Value() {}

func (*UserAttribute_StringValue) isUserAttribute_Value() {}

func (*UserAttribute_BoolValue) isUserAttribute_Value() {}

func (m *UserAttribute) GetValue() isUserAttribute_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UserAttribute) GetIntValue() int64 {
	if x, ok := m.GetValue().(*UserAttribute_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *UserAttribute) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*UserAttribute_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *UserAttribute) GetStringValue() string {
	if x, ok := m.GetValue().(*UserAttribute_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *UserAttribute) GetBoolValue() bool {
	if x, ok := m.GetValue().(*UserAttribute_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserAttribute) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserAttribute_IntValue)(nil),
		(*UserAttribute_DoubleValue)(nil),
		(*UserAttribute_StringValue)(nil),
		(*UserAttribute_BoolValue)(nil),
	}
}

type UserAttributes struct {
	// name of a user
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// public key of tendermint wallet
	PubKey               string           `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	CreationDate         uint64           `protobuf:"varint,3,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	LastModifiedDate     uint64           `protobuf:"varint,4,opt,name=last_modified_date,json=lastModifiedDate,proto3" json:"last_modified_date,omitempty"`
	ExtraFields          []*UserAttribute `protobuf:"bytes,5,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserAttributes) Reset()         { *m = UserAttributes{} }
func (m *UserAttributes) String() string { return proto.CompactTextString(m) }
func (*UserAttributes) ProtoMessage()    {}
func (*UserAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{6}
}

func (m *UserAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAttributes.Unmarshal(m, b)
}
func (m *UserAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAttributes.Marshal(b, m, deterministic)
}
func (m *UserAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAttributes.Merge(m, src)
}
func (m *UserAttributes) XXX_Size() int {
	return xxx_messageInfo_UserAttributes.Size(m)
}
func (m *UserAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_UserAttributes proto.InternalMessageInfo

func (m *UserAttributes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAttributes) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *UserAttributes) GetCreationDate() uint64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *UserAttributes) GetLastModifiedDate() uint64 {
	if m != nil {
		return m.LastModifiedDate
	}
	return 0
}

func (m *UserAttributes) GetExtraFields() []*UserAttribute {
	if m != nil {
		return m.ExtraFields
	}
	return nil
}

type RegisterRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{7}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{8}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AuthenticationResult *AuthenticationResult `protobuf:"bytes,1,opt,name=authentication_result,json=authenticationResult,proto3" json:"authentication_result,omitempty"`
	User                 *User                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{9}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAuthenticationResult() *AuthenticationResult {
	if m != nil {
		return m.AuthenticationResult
	}
	return nil
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AuthenticationResult struct {
	Expiration           uint64   `protobuf:"varint,1,opt,name=expiration,proto3" json:"expiration,omitempty"`
	IssuedAt             uint64   `protobuf:"varint,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResult) Reset()         { *m = AuthenticationResult{} }
func (m *AuthenticationResult) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResult) ProtoMessage()    {}
func (*AuthenticationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{10}
}

func (m *AuthenticationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResult.Unmarshal(m, b)
}
func (m *AuthenticationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResult.Marshal(b, m, deterministic)
}
func (m *AuthenticationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResult.Merge(m, src)
}
func (m *AuthenticationResult) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResult.Size(m)
}
func (m *AuthenticationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResult.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResult proto.InternalMessageInfo

func (m *AuthenticationResult) GetExpiration() uint64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *AuthenticationResult) GetIssuedAt() uint64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *AuthenticationResult) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AuthenticationResult) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshToken struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshToken) Reset()         { *m = RefreshToken{} }
func (m *RefreshToken) String() string { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()    {}
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{11}
}

func (m *RefreshToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshToken.Unmarshal(m, b)
}
func (m *RefreshToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshToken.Marshal(b, m, deterministic)
}
func (m *RefreshToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshToken.Merge(m, src)
}
func (m *RefreshToken) XXX_Size() int {
	return xxx_messageInfo_RefreshToken.Size(m)
}
func (m *RefreshToken) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshToken.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshToken proto.InternalMessageInfo

func (m *RefreshToken) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ConfirmRegistrationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmRegistrationRequest) Reset()         { *m = ConfirmRegistrationRequest{} }
func (m *ConfirmRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmRegistrationRequest) ProtoMessage()    {}
func (*ConfirmRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{12}
}

func (m *ConfirmRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmRegistrationRequest.Unmarshal(m, b)
}
func (m *ConfirmRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmRegistrationRequest.Merge(m, src)
}
func (m *ConfirmRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmRegistrationRequest.Size(m)
}
func (m *ConfirmRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmRegistrationRequest proto.InternalMessageInfo

func (m *ConfirmRegistrationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmRegistrationRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{13}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ConfirmPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPasswordRequest) Reset()         { *m = ConfirmPasswordRequest{} }
func (m *ConfirmPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPasswordRequest) ProtoMessage()    {}
func (*ConfirmPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{14}
}

func (m *ConfirmPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPasswordRequest.Unmarshal(m, b)
}
func (m *ConfirmPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPasswordRequest.Merge(m, src)
}
func (m *ConfirmPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPasswordRequest.Size(m)
}
func (m *ConfirmPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPasswordRequest proto.InternalMessageInfo

func (m *ConfirmPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ConfirmPasswordRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordRequest struct {
	OldPassword          string   `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{15}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangeEmailRequest struct {
	NewEmail             string   `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEmailRequest) Reset()         { *m = ChangeEmailRequest{} }
func (m *ChangeEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeEmailRequest) ProtoMessage()    {}
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{16}
}

func (m *ChangeEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEmailRequest.Unmarshal(m, b)
}
func (m *ChangeEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEmailRequest.Marshal(b, m, deterministic)
}
func (m *ChangeEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEmailRequest.Merge(m, src)
}
func (m *ChangeEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeEmailRequest.Size(m)
}
func (m *ChangeEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEmailRequest proto.InternalMessageInfo

func (m *ChangeEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type UpdateAttributesRequest struct {
	UserAttributes       []*UserAttribute `protobuf:"bytes,1,rep,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateAttributesRequest) Reset()         { *m = UpdateAttributesRequest{} }
func (m *UpdateAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAttributesRequest) ProtoMessage()    {}
func (*UpdateAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{17}
}

func (m *UpdateAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAttributesRequest.Unmarshal(m, b)
}
func (m *UpdateAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAttributesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAttributesRequest.Merge(m, src)
}
func (m *UpdateAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAttributesRequest.Size(m)
}
func (m *UpdateAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAttributesRequest proto.InternalMessageInfo

func (m *UpdateAttributesRequest) GetUserAttributes() []*UserAttribute {
	if m != nil {
		return m.UserAttributes
	}
	return nil
}

type ConfirmEmailRequest struct {
	ConfirmationCode     string   `protobuf:"bytes,1,opt,name=ConfirmationCode,proto3" json:"ConfirmationCode,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=NewEmail,proto3" json:"NewEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailRequest) Reset()         { *m = ConfirmEmailRequest{} }
func (m *ConfirmEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailRequest) ProtoMessage()    {}
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07324a721ebdf9ff, []int{18}
}

func (m *ConfirmEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailRequest.Merge(m, src)
}
func (m *ConfirmEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailRequest.Size(m)
}
func (m *ConfirmEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailRequest proto.InternalMessageInfo

func (m *ConfirmEmailRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

func init() {
	proto.RegisterEnum("usermgr.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*SearchDepositRequest)(nil), "usermgr.SearchDepositRequest")
	proto.RegisterType((*GenerateAddressRequest)(nil), "usermgr.GenerateAddressRequest")
	proto.RegisterType((*GenerateAddressResponse)(nil), "usermgr.GenerateAddressResponse")
	proto.RegisterType((*GetERCDepositResponse)(nil), "usermgr.GetERCDepositResponse")
	proto.RegisterType((*User)(nil), "usermgr.User")
	proto.RegisterType((*UserAttribute)(nil), "usermgr.UserAttribute")
	proto.RegisterType((*UserAttributes)(nil), "usermgr.UserAttributes")
	proto.RegisterType((*RegisterRequest)(nil), "usermgr.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "usermgr.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "usermgr.LoginResponse")
	proto.RegisterType((*AuthenticationResult)(nil), "usermgr.AuthenticationResult")
	proto.RegisterType((*RefreshToken)(nil), "usermgr.RefreshToken")
	proto.RegisterType((*ConfirmRegistrationRequest)(nil), "usermgr.ConfirmRegistrationRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "usermgr.ForgotPasswordRequest")
	proto.RegisterType((*ConfirmPasswordRequest)(nil), "usermgr.ConfirmPasswordRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "usermgr.ChangePasswordRequest")
	proto.RegisterType((*ChangeEmailRequest)(nil), "usermgr.ChangeEmailRequest")
	proto.RegisterType((*UpdateAttributesRequest)(nil), "usermgr.UpdateAttributesRequest")
	proto.RegisterType((*ConfirmEmailRequest)(nil), "usermgr.ConfirmEmailRequest")
}

func init() { proto.RegisterFile("usermgr/v1/micro/usermgr.proto", fileDescriptor_07324a721ebdf9ff) }

var fileDescriptor_07324a721ebdf9ff = []byte{
	// 1191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xed, 0x6e, 0xdb, 0x36,
	0x17, 0xb6, 0x1c, 0x27, 0xb1, 0x8f, 0x3f, 0xe2, 0x32, 0x71, 0x62, 0xb8, 0x6f, 0x53, 0x57, 0x05,
	0x5e, 0x04, 0xed, 0x96, 0xa0, 0x2e, 0xb0, 0x0f, 0x6c, 0x58, 0xe7, 0xd9, 0xce, 0xc7, 0xd6, 0x66,
	0x19, 0x93, 0x66, 0xc0, 0x80, 0xc2, 0x90, 0x2d, 0xc6, 0x11, 0x6a, 0x8b, 0x1a, 0x49, 0x35, 0xcd,
	0x9f, 0xfd, 0xdc, 0x05, 0xec, 0xef, 0x6e, 0x63, 0x77, 0xb1, 0x2b, 0xd9, 0x5d, 0x0c, 0xfc, 0x90,
	0x22, 0x39, 0x72, 0x90, 0xfd, 0xb2, 0x78, 0xf8, 0x9c, 0x87, 0x0f, 0x79, 0xf8, 0x1c, 0x13, 0xb6,
	0x43, 0x4e, 0xd8, 0x6c, 0xc2, 0xf6, 0x3e, 0xbc, 0xd8, 0x9b, 0x79, 0x63, 0x46, 0xf7, 0x4c, 0x60,
	0x37, 0x60, 0x54, 0x50, 0xb4, 0x6a, 0x86, 0xad, 0xf5, 0x31, 0x9d, 0xcd, 0xa8, 0xbf, 0xa7, 0x7f,
	0xf4, 0xac, 0xfd, 0x0d, 0x6c, 0x9c, 0x12, 0x87, 0x8d, 0x2f, 0xfb, 0x24, 0xa0, 0xdc, 0x13, 0x98,
	0xfc, 0x1a, 0x12, 0x2e, 0xd0, 0x06, 0x2c, 0x73, 0xe1, 0x30, 0xd1, 0xb4, 0xda, 0xd6, 0xce, 0x12,
	0xd6, 0x03, 0x54, 0x87, 0x25, 0xe2, 0xbb, 0xcd, 0xbc, 0x8a, 0xc9, 0x4f, 0x7b, 0x1f, 0x36, 0x0f,
	0x88, 0x4f, 0x98, 0x23, 0x48, 0xd7, 0x75, 0x19, 0xe1, 0x3c, 0x62, 0x40, 0x50, 0x10, 0xd7, 0x01,
	0x51, 0x04, 0x25, 0xac, 0xbe, 0x51, 0x13, 0x56, 0x03, 0x46, 0x03, 0xca, 0x89, 0xe2, 0x28, 0xe1,
	0x68, 0x68, 0x8f, 0x61, 0xeb, 0x16, 0x0f, 0x0f, 0xa8, 0xcf, 0x09, 0x6a, 0x43, 0x59, 0x26, 0x3b,
	0x3a, 0x6c, 0xf8, 0x92, 0x21, 0xf4, 0x7f, 0xa8, 0x05, 0x21, 0x93, 0x3c, 0x11, 0x48, 0xb3, 0xcf,
	0x45, 0xed, 0xef, 0xa1, 0x71, 0x40, 0xc4, 0x00, 0xf7, 0xe2, 0xcd, 0x9a, 0x25, 0x5e, 0x40, 0xd1,
	0xd5, 0x21, 0xc9, 0xbf, 0xb4, 0x53, 0xee, 0x34, 0x76, 0x93, 0xc7, 0xb4, 0x1b, 0x25, 0xc4, 0x30,
	0xfb, 0x0f, 0x0b, 0x0a, 0x6f, 0x39, 0x61, 0xa8, 0x06, 0x79, 0xcf, 0x35, 0xaa, 0xf2, 0x9e, 0x2b,
	0x4f, 0x8e, 0xcc, 0x1c, 0x6f, 0x6a, 0x34, 0xe8, 0x01, 0x7a, 0x0e, 0x2b, 0x5c, 0x38, 0x22, 0xe4,
	0xcd, 0xa5, 0xb6, 0xb5, 0x53, 0xeb, 0xac, 0xef, 0x46, 0x55, 0x92, 0x24, 0xa7, 0x6a, 0x0a, 0x1b,
	0x08, 0xfa, 0x1c, 0xc0, 0x11, 0x82, 0x79, 0xa3, 0x50, 0x10, 0xde, 0x2c, 0xb4, 0xad, 0x9d, 0x72,
	0x67, 0x2b, 0x95, 0xd0, 0x8d, 0xa7, 0x71, 0x02, 0x6a, 0xff, 0x65, 0x41, 0x35, 0x35, 0x2d, 0x2b,
	0xf6, 0x9e, 0x5c, 0x1b, 0x79, 0xf2, 0x13, 0x3d, 0x82, 0x92, 0xe7, 0x8b, 0xe1, 0x07, 0x67, 0x1a,
	0xea, 0x2a, 0x2c, 0x1d, 0xe6, 0x70, 0xd1, 0xf3, 0xc5, 0xb9, 0x8c, 0xa0, 0xa7, 0x50, 0x71, 0x69,
	0x38, 0x9a, 0x12, 0x83, 0x90, 0x72, 0xad, 0xc3, 0x1c, 0x2e, 0xeb, 0x68, 0x0c, 0xe2, 0x82, 0x79,
	0xfe, 0xc4, 0x80, 0xa4, 0xc4, 0x92, 0x04, 0xe9, 0xa8, 0x06, 0x3d, 0x06, 0x18, 0x51, 0x3a, 0x35,
	0x90, 0xe5, 0xb6, 0xb5, 0x53, 0x3c, 0xcc, 0xe1, 0x92, 0x8c, 0x29, 0xc0, 0x77, 0xab, 0xb0, 0xac,
	0xe6, 0xec, 0xbf, 0x2d, 0xa8, 0xa5, 0x77, 0x25, 0x6f, 0x8f, 0xef, 0xcc, 0xe2, 0xdb, 0x23, 0xbf,
	0xd1, 0x16, 0xac, 0x06, 0xe1, 0x68, 0x28, 0xf7, 0xa3, 0xcf, 0x76, 0x25, 0x08, 0x47, 0x3f, 0x90,
	0x6b, 0xf4, 0x14, 0xaa, 0x63, 0x46, 0x1c, 0xe1, 0x51, 0x7f, 0xe8, 0x3a, 0x42, 0x8b, 0x2e, 0xe0,
	0x4a, 0x14, 0xec, 0x3b, 0x82, 0xa0, 0x4f, 0x00, 0x4d, 0x1d, 0x2e, 0x86, 0x33, 0xea, 0x7a, 0x17,
	0x1e, 0x71, 0x35, 0xb2, 0xa0, 0x90, 0x75, 0x39, 0xf3, 0xc6, 0x4c, 0x28, 0xf4, 0x97, 0x50, 0x21,
	0x1f, 0x05, 0x73, 0x86, 0x17, 0x1e, 0x99, 0xba, 0xbc, 0xb9, 0xac, 0x6e, 0xc5, 0x66, 0x76, 0x11,
	0x70, 0x59, 0x61, 0xf7, 0x15, 0xd4, 0x3e, 0x81, 0x35, 0x4c, 0x26, 0x1e, 0x17, 0x84, 0x45, 0x5e,
	0x78, 0x02, 0x05, 0x99, 0xa8, 0x76, 0x53, 0xee, 0x54, 0x53, 0x2c, 0x58, 0x4d, 0xa1, 0x16, 0x14,
	0x03, 0x87, 0xf3, 0x2b, 0xca, 0x5c, 0xb3, 0xbb, 0x78, 0x6c, 0x7f, 0x0b, 0x95, 0xd7, 0x74, 0xe2,
	0xf9, 0x09, 0x73, 0xea, 0x2b, 0x66, 0x25, 0xaf, 0xd8, 0x5d, 0x0c, 0xbf, 0x5b, 0x50, 0x35, 0x14,
	0xe6, 0xca, 0x63, 0x68, 0x38, 0xa1, 0xb8, 0x24, 0xbe, 0xf0, 0xc6, 0xfa, 0xe4, 0x18, 0xe1, 0xe1,
	0x54, 0x18, 0x8d, 0x8f, 0x62, 0x8d, 0xdd, 0x14, 0x0a, 0x2b, 0x10, 0xde, 0x70, 0x32, 0xa2, 0xf1,
	0x36, 0xf3, 0x0b, 0xb7, 0x69, 0xff, 0x69, 0xc1, 0x46, 0x16, 0x23, 0xda, 0x06, 0x20, 0x1f, 0x03,
	0x8f, 0xa9, 0x98, 0x12, 0x51, 0xc0, 0x89, 0x08, 0x7a, 0x08, 0x25, 0x8f, 0xf3, 0x90, 0xb8, 0x43,
	0x47, 0xa8, 0x05, 0x0a, 0xb8, 0xa8, 0x03, 0x5d, 0xb9, 0x70, 0xc5, 0x19, 0x8f, 0x09, 0xe7, 0x43,
	0x41, 0xdf, 0x13, 0x5f, 0xd5, 0xbf, 0x84, 0xcb, 0x3a, 0x76, 0x26, 0x43, 0xf2, 0x8e, 0x30, 0x72,
	0xc1, 0x08, 0xbf, 0x34, 0x18, 0x75, 0x67, 0x71, 0xc5, 0x04, 0x15, 0xc8, 0x7e, 0x09, 0x15, 0x9c,
	0x18, 0xdf, 0x4e, 0xb2, 0x32, 0x92, 0x86, 0xd0, 0xea, 0x51, 0xff, 0xc2, 0x63, 0x33, 0x5d, 0x76,
	0x66, 0xb6, 0x75, 0x57, 0xad, 0x9e, 0xc3, 0x83, 0xb1, 0xce, 0xd1, 0x67, 0x3f, 0xa6, 0x6e, 0xd4,
	0x12, 0xeb, 0xc9, 0x89, 0x1e, 0x75, 0x89, 0xfd, 0x29, 0x34, 0xf6, 0x29, 0x9b, 0x50, 0x71, 0x62,
	0xca, 0x79, 0x27, 0xb7, 0xfd, 0x1b, 0x6c, 0x1a, 0x3d, 0xf7, 0xc2, 0xff, 0x27, 0x2d, 0xf2, 0xa4,
	0x7d, 0x72, 0x35, 0x8c, 0x2f, 0x9a, 0x39, 0x69, 0x9f, 0x5c, 0x45, 0x8b, 0xd9, 0xef, 0xa0, 0xd1,
	0xbb, 0x74, 0xfc, 0x09, 0x99, 0x5f, 0xfe, 0x09, 0x54, 0xe8, 0xd4, 0xbd, 0xc9, 0x35, 0x9d, 0x9c,
	0x4e, 0xdd, 0x08, 0x79, 0x8b, 0x3e, 0x7f, 0x9b, 0xfe, 0x05, 0x20, 0x4d, 0x3f, 0x90, 0xea, 0x23,
	0xee, 0x87, 0x50, 0x92, 0x89, 0xc9, 0xed, 0x15, 0x7d, 0x72, 0xa5, 0x30, 0xf6, 0x2f, 0xb0, 0xf5,
	0x36, 0x90, 0x76, 0x4f, 0xb4, 0x4d, 0x93, 0xf7, 0x0a, 0xd6, 0xe4, 0xbd, 0x1c, 0x26, 0xfa, 0xad,
	0x75, 0xa7, 0xd5, 0x6b, 0x61, 0xaa, 0x51, 0xd9, 0xef, 0x60, 0xdd, 0x9c, 0x76, 0x4a, 0xcf, 0x33,
	0xa8, 0xf7, 0xe6, 0xce, 0xce, 0xc8, 0xba, 0x15, 0x97, 0xc6, 0x3d, 0x36, 0x52, 0x23, 0xe3, 0x46,
	0xe3, 0x67, 0x5f, 0x03, 0xdc, 0xfc, 0x41, 0xa0, 0x1a, 0x40, 0xef, 0xc7, 0xe3, 0xfd, 0x23, 0xfc,
	0xe6, 0xe8, 0xf8, 0xa0, 0x9e, 0x43, 0x55, 0x28, 0x99, 0xf1, 0xa0, 0x5f, 0xb7, 0xd0, 0x1a, 0x94,
	0xfb, 0x83, 0x6e, 0xef, 0xec, 0xe8, 0xbc, 0x7b, 0x36, 0xe8, 0xd7, 0xf3, 0x9d, 0x7f, 0x8a, 0xb0,
	0x2a, 0xd3, 0xdf, 0x4c, 0x18, 0xfa, 0x0a, 0x8a, 0x51, 0x5b, 0x42, 0xcd, 0x78, 0x73, 0x73, 0x9d,
	0xaa, 0xb5, 0x9e, 0xfe, 0xdf, 0x1b, 0xcc, 0x02, 0x71, 0x6d, 0xe7, 0xd0, 0x17, 0xb0, 0xac, 0xda,
	0x07, 0x6a, 0xc4, 0x99, 0xc9, 0x8e, 0xd4, 0xda, 0x9c, 0x0f, 0xeb, 0x2e, 0x63, 0xe7, 0xd0, 0x67,
	0xb0, 0xf2, 0x9a, 0x4e, 0x68, 0x28, 0x12, 0xa9, 0x49, 0x8f, 0x2d, 0x5a, 0xf1, 0x10, 0x6a, 0x06,
	0x76, 0x4a, 0x38, 0x97, 0x1d, 0x60, 0x41, 0xfe, 0xdd, 0x9d, 0xca, 0xce, 0xa1, 0x9f, 0xe2, 0x0a,
	0x25, 0xfd, 0x89, 0x9e, 0xc6, 0x79, 0x8b, 0xdd, 0xbb, 0x48, 0xdc, 0x01, 0xd4, 0xd2, 0x8e, 0x44,
	0xdb, 0x31, 0x5b, 0xa6, 0x55, 0x17, 0x11, 0x1d, 0xc1, 0xda, 0x9c, 0x57, 0xd1, 0xe3, 0x79, 0x5d,
	0xf7, 0xa4, 0x3a, 0x80, 0x5a, 0xda, 0x76, 0x09, 0x4d, 0x99, 0x7e, 0x5c, 0x44, 0x34, 0x80, 0xfa,
	0xbc, 0x5b, 0x50, 0xfb, 0xc6, 0x0d, 0xd9, 0x46, 0x6a, 0xa5, 0xbb, 0xbd, 0x9d, 0x43, 0x5d, 0x28,
	0x27, 0x7c, 0x8a, 0x1e, 0xce, 0x89, 0x49, 0xba, 0x65, 0x91, 0x92, 0x57, 0xf0, 0xe0, 0x9c, 0x30,
	0xef, 0xe2, 0xba, 0x9b, 0x68, 0xe4, 0x59, 0xd8, 0x45, 0x04, 0x3d, 0xa8, 0x24, 0xcd, 0x89, 0xfe,
	0x37, 0x7f, 0xb6, 0xf7, 0x51, 0xf1, 0x33, 0xd4, 0x7b, 0xf2, 0x21, 0x41, 0x08, 0x1b, 0x9b, 0xb7,
	0x69, 0xa2, 0x48, 0xd9, 0xaf, 0xdf, 0x56, 0x7b, 0x31, 0x20, 0xb6, 0xc6, 0x3e, 0x54, 0x53, 0xcf,
	0xd1, 0xec, 0xad, 0x6d, 0x27, 0x98, 0x32, 0xde, 0xae, 0x76, 0x0e, 0x9d, 0x40, 0x35, 0xf5, 0x86,
	0x47, 0x37, 0x96, 0xc8, 0x7a, 0xdb, 0xdf, 0x83, 0xb1, 0xa3, 0xbb, 0x4e, 0x9f, 0x08, 0x79, 0x6a,
	0x99, 0xb2, 0xe6, 0xeb, 0x3d, 0x5a, 0x51, 0xb3, 0x2f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0xe4, 0x4d, 0x8d, 0x90, 0x0c, 0x00, 0x00,
}
