// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcmgr/v1/micro/dcmgr.proto

package dcmgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/Ankr-network/dccn-common/protos/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataCenterListResponse struct {
	Id                   string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	DcList               []*common.DataCenter `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_a01223076fab38ba, []int{0}
}
func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (dst *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(dst, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataCenterListResponse) GetDcList() []*common.DataCenter {
	if m != nil {
		return m.DcList
	}
	return nil
}

type NetworkInfoResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfoResponse) Reset()         { *m = NetworkInfoResponse{} }
func (m *NetworkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInfoResponse) ProtoMessage()    {}
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcmgr_a01223076fab38ba, []int{1}
}
func (m *NetworkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfoResponse.Unmarshal(m, b)
}
func (m *NetworkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfoResponse.Marshal(b, m, deterministic)
}
func (dst *NetworkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfoResponse.Merge(dst, src)
}
func (m *NetworkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInfoResponse.Size(m)
}
func (m *NetworkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfoResponse proto.InternalMessageInfo

func (m *NetworkInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DataCenterListResponse)(nil), "dcmgr.DataCenterListResponse")
	proto.RegisterType((*NetworkInfoResponse)(nil), "dcmgr.NetworkInfoResponse")
}

func init() { proto.RegisterFile("dcmgr/v1/micro/dcmgr.proto", fileDescriptor_dcmgr_a01223076fab38ba) }

var fileDescriptor_dcmgr_a01223076fab38ba = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x9b, 0xea, 0x06, 0xde, 0x64, 0x0f, 0x29, 0x8c, 0x12, 0x10, 0x46, 0x9e, 0xea, 0x4b,
	0x3b, 0xeb, 0x17, 0x50, 0x5a, 0x85, 0x81, 0x88, 0x74, 0x6f, 0xbe, 0xd5, 0xf6, 0x94, 0x22, 0x49,
	0xca, 0x35, 0x4c, 0xfc, 0x18, 0x7e, 0x63, 0x31, 0x2d, 0xba, 0x4a, 0xf7, 0x94, 0xdc, 0xe5, 0x97,
	0xdf, 0xf1, 0x3f, 0x10, 0x75, 0xa5, 0xde, 0x28, 0xd9, 0x5f, 0x25, 0xaa, 0xa9, 0xc8, 0x24, 0xae,
	0x8c, 0x5b, 0x32, 0xd6, 0xf0, 0x99, 0x2b, 0x44, 0x50, 0x19, 0xa5, 0x8c, 0x4e, 0xfa, 0xa3, 0x7f,
	0x93, 0xcf, 0xb0, 0xca, 0x4b, 0x5b, 0x66, 0xa8, 0x2d, 0xd2, 0x43, 0xd3, 0xd9, 0x02, 0xbb, 0xd6,
	0xe8, 0x0e, 0xf9, 0x12, 0xfc, 0xa6, 0x0e, 0xfd, 0x35, 0x8b, 0xce, 0x0a, 0xbf, 0xa9, 0xf9, 0x06,
	0xe6, 0x75, 0xf5, 0x43, 0x84, 0x6c, 0x7d, 0x12, 0x2d, 0xd2, 0x30, 0x3e, 0x14, 0xc5, 0x7f, 0x96,
	0x62, 0xe0, 0xe4, 0x25, 0x04, 0x8f, 0x68, 0x3f, 0x0c, 0xbd, 0x6f, 0xf5, 0xab, 0xf9, 0x15, 0x73,
	0x38, 0xd5, 0xa5, 0xc2, 0x90, 0x39, 0xb5, 0xbb, 0xa7, 0x05, 0x40, 0x9e, 0xed, 0x2c, 0x61, 0xa9,
	0x90, 0x78, 0x0e, 0xe7, 0x3b, 0xa4, 0x3d, 0x52, 0xdf, 0xe1, 0xab, 0x7f, 0xa3, 0x06, 0x52, 0x1c,
	0xe9, 0x4b, 0x2f, 0x62, 0x1b, 0x96, 0x7e, 0x31, 0x98, 0xe5, 0xd9, 0xed, 0xd3, 0x96, 0xdf, 0xc3,
	0x72, 0x1c, 0x92, 0x07, 0xe3, 0x9f, 0x77, 0xaa, 0xb5, 0x9f, 0xe2, 0x22, 0xee, 0xb7, 0x36, 0xbd,
	0x10, 0xe9, 0xf1, 0x1b, 0x58, 0x1c, 0x04, 0x9a, 0x96, 0x88, 0x41, 0x32, 0x91, 0x5c, 0x7a, 0x2f,
	0x73, 0x87, 0x5e, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x74, 0x28, 0xe5, 0x67, 0xaf, 0x01, 0x00,
	0x00,
}
