// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dcmgr/v1/micro/dcmgr.proto

package dcmgr

import (
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataCenterListResponse struct {
	DcList               []*common.DataCenterStatus `protobuf:"bytes,1,rep,name=dcList,proto3" json:"dcList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DataCenterListResponse) Reset()         { *m = DataCenterListResponse{} }
func (m *DataCenterListResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterListResponse) ProtoMessage()    {}
func (*DataCenterListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{0}
}

func (m *DataCenterListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterListResponse.Unmarshal(m, b)
}
func (m *DataCenterListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterListResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterListResponse.Merge(m, src)
}
func (m *DataCenterListResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterListResponse.Size(m)
}
func (m *DataCenterListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterListResponse proto.InternalMessageInfo

func (m *DataCenterListResponse) GetDcList() []*common.DataCenterStatus {
	if m != nil {
		return m.DcList
	}
	return nil
}

type NetworkInfoResponse struct {
	UserCount            int32    `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	HostCount            int32    `protobuf:"varint,2,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	EnvironmentCount     int32    `protobuf:"varint,3,opt,name=environment_count,json=environmentCount,proto3" json:"environment_count,omitempty"`
	ContainerCount       int32    `protobuf:"varint,4,opt,name=container_count,json=containerCount,proto3" json:"container_count,omitempty"`
	Traffic              int32    `protobuf:"varint,5,opt,name=traffic,proto3" json:"traffic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkInfoResponse) Reset()         { *m = NetworkInfoResponse{} }
func (m *NetworkInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkInfoResponse) ProtoMessage()    {}
func (*NetworkInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{1}
}

func (m *NetworkInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkInfoResponse.Unmarshal(m, b)
}
func (m *NetworkInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetworkInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkInfoResponse.Merge(m, src)
}
func (m *NetworkInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkInfoResponse.Size(m)
}
func (m *NetworkInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkInfoResponse proto.InternalMessageInfo

func (m *NetworkInfoResponse) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetHostCount() int32 {
	if m != nil {
		return m.HostCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetEnvironmentCount() int32 {
	if m != nil {
		return m.EnvironmentCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *NetworkInfoResponse) GetTraffic() int32 {
	if m != nil {
		return m.Traffic
	}
	return 0
}

type DataCenterLeaderBoardResponse struct {
	List                 []*DataCenterLeaderBoardDetail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DataCenterLeaderBoardResponse) Reset()         { *m = DataCenterLeaderBoardResponse{} }
func (m *DataCenterLeaderBoardResponse) String() string { return proto.CompactTextString(m) }
func (*DataCenterLeaderBoardResponse) ProtoMessage()    {}
func (*DataCenterLeaderBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{2}
}

func (m *DataCenterLeaderBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterLeaderBoardResponse.Unmarshal(m, b)
}
func (m *DataCenterLeaderBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterLeaderBoardResponse.Marshal(b, m, deterministic)
}
func (m *DataCenterLeaderBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterLeaderBoardResponse.Merge(m, src)
}
func (m *DataCenterLeaderBoardResponse) XXX_Size() int {
	return xxx_messageInfo_DataCenterLeaderBoardResponse.Size(m)
}
func (m *DataCenterLeaderBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterLeaderBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterLeaderBoardResponse proto.InternalMessageInfo

func (m *DataCenterLeaderBoardResponse) GetList() []*DataCenterLeaderBoardDetail {
	if m != nil {
		return m.List
	}
	return nil
}

type DataCenterLeaderBoardDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               float64  `protobuf:"fixed64,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataCenterLeaderBoardDetail) Reset()         { *m = DataCenterLeaderBoardDetail{} }
func (m *DataCenterLeaderBoardDetail) String() string { return proto.CompactTextString(m) }
func (*DataCenterLeaderBoardDetail) ProtoMessage()    {}
func (*DataCenterLeaderBoardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_1750e4d9ba65142d, []int{3}
}

func (m *DataCenterLeaderBoardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Unmarshal(m, b)
}
func (m *DataCenterLeaderBoardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Marshal(b, m, deterministic)
}
func (m *DataCenterLeaderBoardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataCenterLeaderBoardDetail.Merge(m, src)
}
func (m *DataCenterLeaderBoardDetail) XXX_Size() int {
	return xxx_messageInfo_DataCenterLeaderBoardDetail.Size(m)
}
func (m *DataCenterLeaderBoardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_DataCenterLeaderBoardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_DataCenterLeaderBoardDetail proto.InternalMessageInfo

func (m *DataCenterLeaderBoardDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataCenterLeaderBoardDetail) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*DataCenterListResponse)(nil), "dcmgr.DataCenterListResponse")
	proto.RegisterType((*NetworkInfoResponse)(nil), "dcmgr.NetworkInfoResponse")
	proto.RegisterType((*DataCenterLeaderBoardResponse)(nil), "dcmgr.DataCenterLeaderBoardResponse")
	proto.RegisterType((*DataCenterLeaderBoardDetail)(nil), "dcmgr.DataCenterLeaderBoardDetail")
}

func init() { proto.RegisterFile("dcmgr/v1/micro/dcmgr.proto", fileDescriptor_1750e4d9ba65142d) }

var fileDescriptor_1750e4d9ba65142d = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x36, 0x31, 0x64, 0x2a, 0xb5, 0xb0, 0x11, 0x25, 0xb8, 0x0a, 0x42, 0x2b, 0x24,
	0x2a, 0x21, 0x25, 0x22, 0x48, 0x5c, 0x38, 0x40, 0xb0, 0x0b, 0xb2, 0x84, 0x4a, 0x65, 0x40, 0x1c,
	0xd1, 0xd6, 0x9e, 0x80, 0x45, 0xf6, 0x8f, 0xd6, 0xeb, 0x54, 0x7d, 0x3e, 0x1e, 0x86, 0x27, 0xe0,
	0x8e, 0xbc, 0x9b, 0xa6, 0x0e, 0x71, 0xd3, 0x43, 0x7b, 0x4a, 0x66, 0xbe, 0x6f, 0x7e, 0xab, 0x19,
	0x6b, 0x06, 0x82, 0x2c, 0xe5, 0x3f, 0xf4, 0x68, 0xfe, 0x62, 0xc4, 0xf3, 0x54, 0xcb, 0x91, 0x0d,
	0x87, 0x4a, 0x4b, 0x23, 0x49, 0xc7, 0x06, 0x41, 0x2f, 0x95, 0x9c, 0x4b, 0x31, 0x72, 0x3f, 0x4e,
	0xa3, 0x27, 0xb0, 0x1f, 0x31, 0xc3, 0x42, 0x14, 0x06, 0xf5, 0xc7, 0xbc, 0x30, 0x09, 0x16, 0x4a,
	0x8a, 0x02, 0xc9, 0x2b, 0xf0, 0xb3, 0xb4, 0xca, 0xf4, 0xbd, 0x27, 0xdb, 0x87, 0x3b, 0xe3, 0xc7,
	0xc3, 0x7a, 0xe1, 0xf0, 0xb2, 0xea, 0xb3, 0x61, 0xa6, 0x2c, 0x92, 0x85, 0x9b, 0xfe, 0xf6, 0xa0,
	0x77, 0x8c, 0xe6, 0x4c, 0xea, 0x5f, 0xb1, 0x98, 0xca, 0x25, 0x6f, 0x00, 0x50, 0x16, 0xa8, 0xbf,
	0xa7, 0xb2, 0x14, 0x15, 0xd3, 0x3b, 0xec, 0x24, 0xdd, 0x2a, 0x13, 0x56, 0x89, 0x4a, 0xfe, 0x29,
	0x0b, 0xb3, 0x90, 0xb7, 0x9c, 0x5c, 0x65, 0x9c, 0xfc, 0x1c, 0xee, 0xa3, 0x98, 0xe7, 0x5a, 0x0a,
	0x8e, 0xe2, 0xc2, 0xb5, 0x6d, 0x5d, 0xf7, 0x6a, 0x82, 0x33, 0x3f, 0x83, 0xbd, 0x54, 0x0a, 0xc3,
	0x72, 0xb1, 0x7c, 0xaf, 0x6d, 0xad, 0xbb, 0xcb, 0xb4, 0x33, 0xf6, 0xe1, 0x8e, 0xd1, 0x6c, 0x3a,
	0xcd, 0xd3, 0x7e, 0xc7, 0x1a, 0x2e, 0x42, 0xfa, 0x0d, 0x06, 0xb5, 0xb9, 0x20, 0xcb, 0x50, 0xbf,
	0x93, 0x4c, 0x67, 0xb5, 0xf1, 0xb4, 0x67, 0x97, 0xc3, 0xa1, 0x43, 0x37, 0xf0, 0xc6, 0x9a, 0x08,
	0x0d, 0xcb, 0x67, 0x89, 0xf5, 0xd3, 0x18, 0x0e, 0x36, 0x98, 0x08, 0x81, 0xb6, 0x60, 0x1c, 0xed,
	0x7c, 0xba, 0x89, 0xfd, 0x4f, 0xf6, 0xc1, 0x17, 0x25, 0x3f, 0x45, 0x6d, 0xc7, 0xe2, 0x25, 0x8b,
	0x68, 0xfc, 0xb7, 0x0d, 0x5b, 0x51, 0x48, 0x8e, 0xa0, 0x1b, 0x6a, 0x64, 0x06, 0x27, 0x4a, 0x91,
	0x83, 0xd5, 0xaf, 0x34, 0x51, 0x2a, 0x42, 0x35, 0x93, 0xe7, 0xd5, 0x70, 0x82, 0x47, 0x6b, 0xa2,
	0x6b, 0x27, 0x45, 0xda, 0xaa, 0x30, 0x5f, 0x55, 0x76, 0x1b, 0x98, 0x08, 0x67, 0x78, 0x53, 0xcc,
	0x07, 0xd8, 0x73, 0x4d, 0x1d, 0x33, 0x8e, 0x85, 0x62, 0x29, 0x92, 0x87, 0xab, 0xfe, 0xa5, 0x70,
	0x2d, 0xc8, 0xb5, 0x75, 0x0b, 0x20, 0xd7, 0xd8, 0x4d, 0x41, 0xaf, 0xc1, 0x77, 0x2b, 0x43, 0x7a,
	0x6b, 0xb6, 0x38, 0x0a, 0x82, 0xf5, 0xda, 0x52, 0xb8, 0x02, 0xda, 0x22, 0x6f, 0xc0, 0x8f, 0x45,
	0x6e, 0xa2, 0x90, 0xf4, 0xaf, 0xda, 0xc7, 0xcd, 0xaf, 0x4f, 0xe0, 0xee, 0xa7, 0x39, 0xea, 0x79,
	0x8e, 0x67, 0xff, 0xbf, 0x7f, 0xc4, 0x95, 0x39, 0x0f, 0xae, 0xd9, 0x73, 0xda, 0x1a, 0xff, 0xf1,
	0xa0, 0x13, 0x85, 0x93, 0x93, 0x98, 0xbc, 0x87, 0xdd, 0xd5, 0xeb, 0xd1, 0x8c, 0x1c, 0xac, 0x6f,
	0x47, 0xed, 0xd2, 0xd0, 0x16, 0xf9, 0x02, 0x0f, 0x1a, 0x97, 0xa2, 0x19, 0xf7, 0x74, 0xd3, 0xb2,
	0xd5, 0xa8, 0x6f, 0x61, 0xa7, 0x76, 0x88, 0x9a, 0x59, 0xc1, 0x82, 0xd5, 0x70, 0xb1, 0x68, 0xeb,
	0xd4, 0xb7, 0xd6, 0x97, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xc7, 0x38, 0x91, 0x5e, 0x05,
	0x00, 0x00,
}
