// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgr/v1/usermgr.proto

package srv_v1_usermgr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_44d6fd02c19a32ce, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Email struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_44d6fd02c19a32ce, []int{1}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type User struct {
	// id self-increase, de
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name should be unique
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// nickname show on UI
	Nickname string `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// email user's email, unique.
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// password string
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// balance user's balance in account
	Balance int32 `protobuf:"varint,7,opt,name=balance,proto3" json:"balance,omitempty"`
	// is_deleted user's status
	IsDeleted bool `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// token jwt token string
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_44d6fd02c19a32ce, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetBalance() int32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *User) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_44d6fd02c19a32ce, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_usermgr_44d6fd02c19a32ce, []int{4}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "srv.v1.usermgr.LoginRequest")
	proto.RegisterType((*Email)(nil), "srv.v1.usermgr.Email")
	proto.RegisterType((*User)(nil), "srv.v1.usermgr.User")
	proto.RegisterType((*Response)(nil), "srv.v1.usermgr.Response")
	proto.RegisterType((*Token)(nil), "srv.v1.usermgr.Token")
}

func init() { proto.RegisterFile("usermgr/v1/usermgr.proto", fileDescriptor_usermgr_44d6fd02c19a32ce) }

var fileDescriptor_usermgr_44d6fd02c19a32ce = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xa5, 0x85, 0x42, 0x99, 0xdf, 0x2f, 0x1c, 0x26, 0x98, 0x6c, 0x88, 0x24, 0xa4, 0x27, 0x4e,
	0x25, 0xa8, 0x17, 0x4d, 0x4c, 0x48, 0xd4, 0x78, 0x51, 0x0f, 0x8d, 0x7a, 0x35, 0x85, 0x8e, 0x64,
	0x03, 0x74, 0x71, 0x77, 0x81, 0xf8, 0xc9, 0xfc, 0x08, 0x7e, 0x2d, 0xb3, 0xdb, 0xf2, 0xd7, 0xe2,
	0x6d, 0xdf, 0x9b, 0x37, 0xf3, 0xde, 0x4c, 0x0b, 0x6c, 0xa1, 0x48, 0xce, 0xc6, 0xb2, 0xb7, 0xec,
	0xf7, 0xf2, 0x67, 0x38, 0x97, 0x42, 0x0b, 0x6c, 0x28, 0xb9, 0x0c, 0x97, 0xfd, 0x30, 0x67, 0x83,
	0x01, 0xfc, 0x7f, 0x10, 0x63, 0x9e, 0x46, 0xf4, 0xb1, 0x20, 0xa5, 0xb1, 0x09, 0x1e, 0xcd, 0x62,
	0x3e, 0x65, 0x4e, 0xc7, 0xe9, 0xd6, 0xa3, 0x0c, 0x60, 0x0b, 0xfc, 0x79, 0xac, 0xd4, 0x4a, 0xc8,
	0x84, 0xb9, 0xb6, 0xb0, 0xc1, 0x41, 0x1b, 0xbc, 0x3b, 0x2b, 0x2a, 0x6c, 0x0d, 0xbe, 0x1d, 0xa8,
	0xbc, 0x28, 0x92, 0xd8, 0x00, 0x97, 0x27, 0xb6, 0x56, 0x8e, 0x5c, 0x9e, 0x20, 0x42, 0x25, 0x8d,
	0x67, 0x94, 0xcf, 0xb3, 0x6f, 0xe3, 0x93, 0xf2, 0xd1, 0xc4, 0xf2, 0x95, 0xcc, 0x67, 0x8d, 0xb7,
	0xe3, 0xbd, 0x63, 0xc9, 0xaa, 0xfb, 0xc9, 0x90, 0x41, 0x6d, 0x18, 0x4f, 0xe3, 0x74, 0x44, 0xac,
	0xd6, 0x71, 0xba, 0x5e, 0xb4, 0x86, 0xd8, 0x06, 0xe0, 0xea, 0x2d, 0xa1, 0x29, 0x69, 0x4a, 0x98,
	0xdf, 0x71, 0xba, 0x7e, 0x54, 0xe7, 0xea, 0x36, 0x23, 0x8c, 0x95, 0x16, 0x13, 0x4a, 0x59, 0x3d,
	0xb3, 0xb2, 0x20, 0x00, 0xf0, 0x23, 0x52, 0x73, 0x91, 0x2a, 0x32, 0x4b, 0x3f, 0x1b, 0x72, 0x2b,
	0x75, 0x76, 0xa4, 0x67, 0x5f, 0x2e, 0xd4, 0xcc, 0xd2, 0x8f, 0x63, 0x89, 0xd7, 0xe0, 0xd9, 0x0b,
	0xe3, 0x69, 0xb8, 0x7f, 0xfb, 0x70, 0xf7, 0xf0, 0xad, 0xe6, 0x61, 0xd5, 0xf4, 0x07, 0x25, 0xbc,
	0x82, 0xea, 0x8d, 0xa4, 0x58, 0x13, 0x16, 0x2a, 0x5a, 0xec, 0x90, 0xdd, 0x64, 0x2c, 0xe1, 0x05,
	0x94, 0xef, 0x49, 0xe3, 0xc9, 0xa1, 0xc4, 0x7e, 0xaf, 0xa3, 0x8e, 0x97, 0xe0, 0x3f, 0xd1, 0x2a,
	0x5f, 0xaf, 0xd0, 0xf3, 0xd7, 0x40, 0x2b, 0x0e, 0x4a, 0x38, 0x80, 0x7f, 0xaf, 0x24, 0xf9, 0xfb,
	0x67, 0xd6, 0x5d, 0xac, 0xfb, 0x2b, 0xf2, 0xb0, 0x6a, 0x7f, 0xd3, 0xf3, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb4, 0x35, 0x68, 0x85, 0xc2, 0x02, 0x00, 0x00,
}
