// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appmgr/v1/grpc/appmgr.proto

package appmgr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The dccn client request message containing the user's token
type CreateAppRequest struct {
	App                  *common.App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{0}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetApp() *common.App {
	if m != nil {
		return m.App
	}
	return nil
}

type CreateAppResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{1}
}

func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(m, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppListRequest struct {
	AppFilter            *AppFilter `protobuf:"bytes,1,opt,name=app_filter,json=appFilter,proto3" json:"app_filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AppListRequest) Reset()         { *m = AppListRequest{} }
func (m *AppListRequest) String() string { return proto.CompactTextString(m) }
func (*AppListRequest) ProtoMessage()    {}
func (*AppListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{2}
}

func (m *AppListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListRequest.Unmarshal(m, b)
}
func (m *AppListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListRequest.Marshal(b, m, deterministic)
}
func (m *AppListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListRequest.Merge(m, src)
}
func (m *AppListRequest) XXX_Size() int {
	return xxx_messageInfo_AppListRequest.Size(m)
}
func (m *AppListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppListRequest proto.InternalMessageInfo

func (m *AppListRequest) GetAppFilter() *AppFilter {
	if m != nil {
		return m.AppFilter
	}
	return nil
}

type AppListResponse struct {
	Apps                 []*common.App `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{3}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetApps() []*common.App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type AppFilter struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppFilter) Reset()         { *m = AppFilter{} }
func (m *AppFilter) String() string { return proto.CompactTextString(m) }
func (*AppFilter) ProtoMessage()    {}
func (*AppFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{4}
}

func (m *AppFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppFilter.Unmarshal(m, b)
}
func (m *AppFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppFilter.Marshal(b, m, deterministic)
}
func (m *AppFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppFilter.Merge(m, src)
}
func (m *AppFilter) XXX_Size() int {
	return xxx_messageInfo_AppFilter.Size(m)
}
func (m *AppFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AppFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AppFilter proto.InternalMessageInfo

func (m *AppFilter) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppID struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppID) Reset()         { *m = AppID{} }
func (m *AppID) String() string { return proto.CompactTextString(m) }
func (*AppID) ProtoMessage()    {}
func (*AppID) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{5}
}

func (m *AppID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppID.Unmarshal(m, b)
}
func (m *AppID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppID.Marshal(b, m, deterministic)
}
func (m *AppID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppID.Merge(m, src)
}
func (m *AppID) XXX_Size() int {
	return xxx_messageInfo_AppID.Size(m)
}
func (m *AppID) XXX_DiscardUnknown() {
	xxx_messageInfo_AppID.DiscardUnknown(m)
}

var xxx_messageInfo_AppID proto.InternalMessageInfo

func (m *AppID) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type UpdateAppRequest struct {
	App                  *common.App `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{6}
}

func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetApp() *common.App {
	if m != nil {
		return m.App
	}
	return nil
}

type AppOverviewResponse struct {
	ClusterCount         int32    `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	EnvironmentCount     int32    `protobuf:"varint,2,opt,name=environment_count,json=environmentCount,proto3" json:"environment_count,omitempty"`
	RegionCount          int32    `protobuf:"varint,3,opt,name=region_count,json=regionCount,proto3" json:"region_count,omitempty"`
	TotalAppCount        int32    `protobuf:"varint,4,opt,name=total_app_count,json=totalAppCount,proto3" json:"total_app_count,omitempty"`
	HealthAppCount       int32    `protobuf:"varint,5,opt,name=health_app_count,json=healthAppCount,proto3" json:"health_app_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppOverviewResponse) Reset()         { *m = AppOverviewResponse{} }
func (m *AppOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*AppOverviewResponse) ProtoMessage()    {}
func (*AppOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{7}
}

func (m *AppOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppOverviewResponse.Unmarshal(m, b)
}
func (m *AppOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppOverviewResponse.Marshal(b, m, deterministic)
}
func (m *AppOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppOverviewResponse.Merge(m, src)
}
func (m *AppOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_AppOverviewResponse.Size(m)
}
func (m *AppOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppOverviewResponse proto.InternalMessageInfo

func (m *AppOverviewResponse) GetClusterCount() int32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *AppOverviewResponse) GetEnvironmentCount() int32 {
	if m != nil {
		return m.EnvironmentCount
	}
	return 0
}

func (m *AppOverviewResponse) GetRegionCount() int32 {
	if m != nil {
		return m.RegionCount
	}
	return 0
}

func (m *AppOverviewResponse) GetTotalAppCount() int32 {
	if m != nil {
		return m.TotalAppCount
	}
	return 0
}

func (m *AppOverviewResponse) GetHealthAppCount() int32 {
	if m != nil {
		return m.HealthAppCount
	}
	return 0
}

type AppLeaderBoardResponse struct {
	List                 []*AppLeaderBoardDetail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AppLeaderBoardResponse) Reset()         { *m = AppLeaderBoardResponse{} }
func (m *AppLeaderBoardResponse) String() string { return proto.CompactTextString(m) }
func (*AppLeaderBoardResponse) ProtoMessage()    {}
func (*AppLeaderBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{8}
}

func (m *AppLeaderBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLeaderBoardResponse.Unmarshal(m, b)
}
func (m *AppLeaderBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLeaderBoardResponse.Marshal(b, m, deterministic)
}
func (m *AppLeaderBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLeaderBoardResponse.Merge(m, src)
}
func (m *AppLeaderBoardResponse) XXX_Size() int {
	return xxx_messageInfo_AppLeaderBoardResponse.Size(m)
}
func (m *AppLeaderBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLeaderBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppLeaderBoardResponse proto.InternalMessageInfo

func (m *AppLeaderBoardResponse) GetList() []*AppLeaderBoardDetail {
	if m != nil {
		return m.List
	}
	return nil
}

type AppLeaderBoardDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               float64  `protobuf:"fixed64,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppLeaderBoardDetail) Reset()         { *m = AppLeaderBoardDetail{} }
func (m *AppLeaderBoardDetail) String() string { return proto.CompactTextString(m) }
func (*AppLeaderBoardDetail) ProtoMessage()    {}
func (*AppLeaderBoardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{9}
}

func (m *AppLeaderBoardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLeaderBoardDetail.Unmarshal(m, b)
}
func (m *AppLeaderBoardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLeaderBoardDetail.Marshal(b, m, deterministic)
}
func (m *AppLeaderBoardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLeaderBoardDetail.Merge(m, src)
}
func (m *AppLeaderBoardDetail) XXX_Size() int {
	return xxx_messageInfo_AppLeaderBoardDetail.Size(m)
}
func (m *AppLeaderBoardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLeaderBoardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AppLeaderBoardDetail proto.InternalMessageInfo

func (m *AppLeaderBoardDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppLeaderBoardDetail) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CreateChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartFile            []byte   `protobuf:"bytes,4,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChartRequest) Reset()         { *m = CreateChartRequest{} }
func (m *CreateChartRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChartRequest) ProtoMessage()    {}
func (*CreateChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{10}
}

func (m *CreateChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChartRequest.Unmarshal(m, b)
}
func (m *CreateChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChartRequest.Marshal(b, m, deterministic)
}
func (m *CreateChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChartRequest.Merge(m, src)
}
func (m *CreateChartRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChartRequest.Size(m)
}
func (m *CreateChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChartRequest proto.InternalMessageInfo

func (m *CreateChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *CreateChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *CreateChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *CreateChartRequest) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type ChartListRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	Filter               string   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartListRequest) Reset()         { *m = ChartListRequest{} }
func (m *ChartListRequest) String() string { return proto.CompactTextString(m) }
func (*ChartListRequest) ProtoMessage()    {}
func (*ChartListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{11}
}

func (m *ChartListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListRequest.Unmarshal(m, b)
}
func (m *ChartListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListRequest.Marshal(b, m, deterministic)
}
func (m *ChartListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListRequest.Merge(m, src)
}
func (m *ChartListRequest) XXX_Size() int {
	return xxx_messageInfo_ChartListRequest.Size(m)
}
func (m *ChartListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListRequest proto.InternalMessageInfo

func (m *ChartListRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *ChartListRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ChartListResponse struct {
	Charts               []*common.Chart `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChartListResponse) Reset()         { *m = ChartListResponse{} }
func (m *ChartListResponse) String() string { return proto.CompactTextString(m) }
func (*ChartListResponse) ProtoMessage()    {}
func (*ChartListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{12}
}

func (m *ChartListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListResponse.Unmarshal(m, b)
}
func (m *ChartListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListResponse.Marshal(b, m, deterministic)
}
func (m *ChartListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListResponse.Merge(m, src)
}
func (m *ChartListResponse) XXX_Size() int {
	return xxx_messageInfo_ChartListResponse.Size(m)
}
func (m *ChartListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListResponse proto.InternalMessageInfo

func (m *ChartListResponse) GetCharts() []*common.Chart {
	if m != nil {
		return m.Charts
	}
	return nil
}

type ChartDetailRequest struct {
	Chart                *common.Chart `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	ShowVersion          string        `protobuf:"bytes,2,opt,name=show_version,json=showVersion,proto3" json:"show_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChartDetailRequest) Reset()         { *m = ChartDetailRequest{} }
func (m *ChartDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ChartDetailRequest) ProtoMessage()    {}
func (*ChartDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{13}
}

func (m *ChartDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailRequest.Unmarshal(m, b)
}
func (m *ChartDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailRequest.Marshal(b, m, deterministic)
}
func (m *ChartDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailRequest.Merge(m, src)
}
func (m *ChartDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ChartDetailRequest.Size(m)
}
func (m *ChartDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailRequest proto.InternalMessageInfo

func (m *ChartDetailRequest) GetChart() *common.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *ChartDetailRequest) GetShowVersion() string {
	if m != nil {
		return m.ShowVersion
	}
	return ""
}

type ChartDetailResponse struct {
	Chartdetail          []*common.ChartDetail `protobuf:"bytes,1,rep,name=chartdetail,proto3" json:"chartdetail,omitempty"`
	ShowReadme           string                `protobuf:"bytes,2,opt,name=show_readme,json=showReadme,proto3" json:"show_readme,omitempty"`
	ShowValues           string                `protobuf:"bytes,3,opt,name=show_values,json=showValues,proto3" json:"show_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ChartDetailResponse) Reset()         { *m = ChartDetailResponse{} }
func (m *ChartDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ChartDetailResponse) ProtoMessage()    {}
func (*ChartDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{14}
}

func (m *ChartDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailResponse.Unmarshal(m, b)
}
func (m *ChartDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailResponse.Marshal(b, m, deterministic)
}
func (m *ChartDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailResponse.Merge(m, src)
}
func (m *ChartDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ChartDetailResponse.Size(m)
}
func (m *ChartDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailResponse proto.InternalMessageInfo

func (m *ChartDetailResponse) GetChartdetail() []*common.ChartDetail {
	if m != nil {
		return m.Chartdetail
	}
	return nil
}

func (m *ChartDetailResponse) GetShowReadme() string {
	if m != nil {
		return m.ShowReadme
	}
	return ""
}

func (m *ChartDetailResponse) GetShowValues() string {
	if m != nil {
		return m.ShowValues
	}
	return ""
}

type DeleteChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteChartRequest) Reset()         { *m = DeleteChartRequest{} }
func (m *DeleteChartRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChartRequest) ProtoMessage()    {}
func (*DeleteChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{15}
}

func (m *DeleteChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteChartRequest.Unmarshal(m, b)
}
func (m *DeleteChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteChartRequest.Marshal(b, m, deterministic)
}
func (m *DeleteChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteChartRequest.Merge(m, src)
}
func (m *DeleteChartRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteChartRequest.Size(m)
}
func (m *DeleteChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteChartRequest proto.InternalMessageInfo

func (m *DeleteChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DeleteChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DeleteChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type CreateNamespaceRequest struct {
	Namespace            *common.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{16}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetNamespace() *common.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type ListNamespaceRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNamespaceRequest) Reset()         { *m = ListNamespaceRequest{} }
func (m *ListNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceRequest) ProtoMessage()    {}
func (*ListNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{17}
}

func (m *ListNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceRequest.Unmarshal(m, b)
}
func (m *ListNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *ListNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceRequest.Merge(m, src)
}
func (m *ListNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceRequest.Size(m)
}
func (m *ListNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceRequest proto.InternalMessageInfo

func (m *ListNamespaceRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListNamespaceResponse struct {
	Namespace            []*common.Namespace `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListNamespaceResponse) Reset()         { *m = ListNamespaceResponse{} }
func (m *ListNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespaceResponse) ProtoMessage()    {}
func (*ListNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{18}
}

func (m *ListNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespaceResponse.Unmarshal(m, b)
}
func (m *ListNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *ListNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespaceResponse.Merge(m, src)
}
func (m *ListNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_ListNamespaceResponse.Size(m)
}
func (m *ListNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespaceResponse proto.InternalMessageInfo

func (m *ListNamespaceResponse) GetNamespace() []*common.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type UpdateNamespaceRequest struct {
	Namespace            *common.Namespace `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{19}
}

func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(m, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

func (m *UpdateNamespaceRequest) GetNamespace() *common.Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type DeleteNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b7c3ca3eef8e484, []int{20}
}

func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAppRequest)(nil), "appmgr.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "appmgr.CreateAppResponse")
	proto.RegisterType((*AppListRequest)(nil), "appmgr.AppListRequest")
	proto.RegisterType((*AppListResponse)(nil), "appmgr.AppListResponse")
	proto.RegisterType((*AppFilter)(nil), "appmgr.AppFilter")
	proto.RegisterType((*AppID)(nil), "appmgr.AppID")
	proto.RegisterType((*UpdateAppRequest)(nil), "appmgr.UpdateAppRequest")
	proto.RegisterType((*AppOverviewResponse)(nil), "appmgr.AppOverviewResponse")
	proto.RegisterType((*AppLeaderBoardResponse)(nil), "appmgr.AppLeaderBoardResponse")
	proto.RegisterType((*AppLeaderBoardDetail)(nil), "appmgr.AppLeaderBoardDetail")
	proto.RegisterType((*CreateChartRequest)(nil), "appmgr.CreateChartRequest")
	proto.RegisterType((*ChartListRequest)(nil), "appmgr.ChartListRequest")
	proto.RegisterType((*ChartListResponse)(nil), "appmgr.ChartListResponse")
	proto.RegisterType((*ChartDetailRequest)(nil), "appmgr.ChartDetailRequest")
	proto.RegisterType((*ChartDetailResponse)(nil), "appmgr.ChartDetailResponse")
	proto.RegisterType((*DeleteChartRequest)(nil), "appmgr.DeleteChartRequest")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "appmgr.CreateNamespaceRequest")
	proto.RegisterType((*ListNamespaceRequest)(nil), "appmgr.ListNamespaceRequest")
	proto.RegisterType((*ListNamespaceResponse)(nil), "appmgr.ListNamespaceResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "appmgr.UpdateNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "appmgr.DeleteNamespaceRequest")
}

func init() { proto.RegisterFile("appmgr/v1/grpc/appmgr.proto", fileDescriptor_8b7c3ca3eef8e484) }

var fileDescriptor_8b7c3ca3eef8e484 = []byte{
	// 918 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5b, 0x8f, 0xdb, 0x44,
	0x14, 0x5e, 0x6f, 0x36, 0x69, 0x7d, 0xb2, 0x97, 0xec, 0x6c, 0x9b, 0x6e, 0xb3, 0x74, 0x29, 0x53,
	0x81, 0x16, 0x2a, 0x25, 0xdb, 0x22, 0x54, 0x24, 0xfa, 0x50, 0x27, 0xa1, 0x34, 0x08, 0x76, 0x91,
	0x25, 0xf6, 0x35, 0x9a, 0xb5, 0xa7, 0x89, 0x25, 0x5f, 0x86, 0xb1, 0x93, 0x8a, 0x3f, 0xc1, 0x13,
	0x3f, 0x8f, 0x3f, 0xc2, 0x1b, 0x9a, 0x8b, 0xed, 0x89, 0x63, 0xc3, 0x0a, 0x21, 0x9e, 0xec, 0x39,
	0xe7, 0x3b, 0x97, 0x39, 0x97, 0x6f, 0xe0, 0x8c, 0x30, 0x16, 0x2d, 0xf8, 0x68, 0xfd, 0x62, 0xb4,
	0xe0, 0xcc, 0x1b, 0xa9, 0xe3, 0x90, 0xf1, 0x24, 0x4b, 0x50, 0x47, 0x9d, 0x06, 0x27, 0x5e, 0x12,
	0x45, 0x49, 0x3c, 0x52, 0x1f, 0xa5, 0xc4, 0xaf, 0xa0, 0x37, 0xe1, 0x94, 0x64, 0xd4, 0x61, 0xcc,
	0xa5, 0xbf, 0xac, 0x68, 0x9a, 0xa1, 0x67, 0xd0, 0x22, 0x8c, 0x9d, 0x5a, 0x4f, 0xad, 0x8b, 0xee,
	0xcb, 0xe3, 0xa1, 0x89, 0x1f, 0x0a, 0x98, 0xd0, 0xe2, 0x2f, 0xe0, 0xd8, 0x30, 0x4c, 0x59, 0x12,
	0xa7, 0x14, 0x3d, 0x04, 0x11, 0x6c, 0x1e, 0xf8, 0xd2, 0xd8, 0x76, 0xdb, 0x84, 0xb1, 0x99, 0x8f,
	0xc7, 0x70, 0xe8, 0x30, 0xf6, 0x43, 0x90, 0x66, 0x79, 0x88, 0x4b, 0x00, 0x01, 0x7c, 0x1f, 0x84,
	0x19, 0xe5, 0x45, 0x24, 0x9d, 0xb6, 0xc3, 0xd8, 0x5b, 0xa9, 0x70, 0x6d, 0x92, 0xff, 0xe2, 0xaf,
	0xe1, 0xa8, 0xf0, 0xa1, 0xa3, 0x7d, 0x0a, 0x7b, 0x84, 0xb1, 0xf4, 0xd4, 0x7a, 0xda, 0xaa, 0x4f,
	0x54, 0xaa, 0x31, 0x06, 0xbb, 0xf0, 0xd8, 0x94, 0xe1, 0x39, 0xb4, 0x1d, 0xc6, 0x66, 0xd3, 0x26,
	0xfd, 0x2b, 0xe8, 0xfd, 0xcc, 0xfc, 0x7f, 0x51, 0xa6, 0x3f, 0x2c, 0x38, 0x71, 0x18, 0xbb, 0x5e,
	0x53, 0xbe, 0x0e, 0xe8, 0x87, 0x22, 0xf7, 0x67, 0x70, 0xe0, 0x85, 0xab, 0x34, 0xa3, 0x7c, 0xee,
	0x25, 0xab, 0x38, 0x93, 0x6e, 0xda, 0xee, 0xbe, 0x16, 0x4e, 0x84, 0x0c, 0x3d, 0x87, 0x63, 0x1a,
	0xaf, 0x03, 0x9e, 0xc4, 0x11, 0x8d, 0x33, 0x0d, 0xdc, 0x95, 0xc0, 0x9e, 0xa1, 0x50, 0xe0, 0x4f,
	0x60, 0x9f, 0xd3, 0x45, 0x90, 0xc4, 0x1a, 0xd7, 0x92, 0xb8, 0xae, 0x92, 0x29, 0xc8, 0x67, 0x70,
	0x94, 0x25, 0x19, 0x09, 0xe7, 0xe2, 0x8a, 0x0a, 0xb5, 0x27, 0x51, 0x07, 0x52, 0xec, 0x30, 0xa6,
	0x70, 0x17, 0xd0, 0x5b, 0x52, 0x12, 0x66, 0x4b, 0x03, 0xd8, 0x96, 0xc0, 0x43, 0x25, 0xcf, 0x91,
	0xf8, 0x7b, 0xe8, 0x8b, 0xae, 0x50, 0xe2, 0x53, 0x3e, 0x4e, 0x08, 0xf7, 0x8b, 0x0b, 0x5e, 0xc2,
	0x5e, 0x18, 0xa4, 0x99, 0x6e, 0xce, 0x47, 0x46, 0x6f, 0x0d, 0xf4, 0x94, 0x66, 0x24, 0x08, 0x5d,
	0x89, 0xc4, 0x63, 0x78, 0x50, 0xa7, 0x45, 0x08, 0xf6, 0x62, 0x12, 0x51, 0xdd, 0x10, 0xf9, 0x8f,
	0xfa, 0xd0, 0x89, 0x57, 0xd1, 0x2d, 0xe5, 0xb2, 0x1c, 0x96, 0xab, 0x4f, 0xf8, 0x37, 0x0b, 0x90,
	0x1a, 0xcb, 0xc9, 0x92, 0xf0, 0x62, 0xdc, 0x9e, 0x00, 0x78, 0xe2, 0x3c, 0xe7, 0x94, 0x25, 0xda,
	0x91, 0xed, 0x29, 0x04, 0x4b, 0xd0, 0x19, 0xa8, 0xc3, 0x7c, 0xad, 0x1d, 0xda, 0xee, 0x7d, 0x29,
	0xb8, 0xa1, 0xbc, 0xb4, 0x95, 0x49, 0xb4, 0x0c, 0xdb, 0x2b, 0x91, 0x49, 0xa1, 0x7e, 0x1f, 0x84,
	0x54, 0x96, 0x73, 0x5f, 0xab, 0xdf, 0x06, 0x21, 0xc5, 0x33, 0xe8, 0xc9, 0x4c, 0xcc, 0xe1, 0xff,
	0x87, 0x6c, 0xfa, 0xd0, 0xd1, 0x7b, 0xa1, 0x52, 0xd1, 0x27, 0xfc, 0x06, 0x8e, 0x0d, 0x57, 0xba,
	0xcc, 0xcf, 0xa1, 0x23, 0x2d, 0xf3, 0x2d, 0x38, 0xd9, 0x9c, 0x43, 0x55, 0x05, 0x0d, 0xc1, 0xb7,
	0x80, 0xa4, 0x40, 0x97, 0x5d, 0xa7, 0xf3, 0x39, 0xb4, 0xa5, 0x5e, 0x4f, 0x72, 0xad, 0x07, 0x85,
	0x10, 0x33, 0x96, 0x2e, 0x93, 0x0f, 0xa2, 0x4e, 0x69, 0x90, 0xc4, 0x3a, 0xc1, 0xae, 0x90, 0xdd,
	0x28, 0x11, 0xfe, 0xdd, 0x82, 0x93, 0x8d, 0x20, 0x3a, 0xd1, 0x6f, 0xa0, 0x2b, 0x7d, 0xf8, 0x52,
	0xac, 0xb3, 0x7d, 0x5c, 0x13, 0x4b, 0xdb, 0x99, 0x68, 0xf4, 0x31, 0xc8, 0x18, 0x73, 0x4e, 0x89,
	0x1f, 0x51, 0x1d, 0x16, 0x84, 0xc8, 0x95, 0x92, 0x02, 0xb0, 0x26, 0xe1, 0x8a, 0xa6, 0xba, 0x4b,
	0x12, 0x70, 0x23, 0x25, 0x38, 0x01, 0x34, 0xa5, 0x21, 0xfd, 0xdf, 0xe6, 0x02, 0x5f, 0x43, 0x5f,
	0x0d, 0xa2, 0x38, 0xa5, 0x8c, 0x78, 0x34, 0x0f, 0xfa, 0x15, 0xd8, 0x71, 0x2e, 0xd3, 0x35, 0x7f,
	0xb4, 0x59, 0x87, 0xd2, 0xa4, 0x44, 0xe2, 0x21, 0x3c, 0x10, 0x9d, 0xdf, 0x72, 0x57, 0x8e, 0x8b,
	0xb5, 0x31, 0x2e, 0x57, 0xf0, 0xb0, 0x82, 0xd7, 0x9d, 0xa8, 0xc4, 0x6f, 0xdd, 0x31, 0xfe, 0x35,
	0xf4, 0x15, 0x05, 0xfe, 0x57, 0x17, 0xba, 0x80, 0xbe, 0x6a, 0xc9, 0x96, 0xc3, 0x43, 0xd8, 0x2d,
	0x08, 0x78, 0x37, 0xf0, 0x5f, 0xfe, 0x79, 0x0f, 0x3a, 0x0e, 0x63, 0x3f, 0x2e, 0x38, 0x1a, 0x83,
	0x5d, 0x3c, 0x3b, 0xe8, 0x34, 0x67, 0x95, 0xea, 0x13, 0x36, 0x78, 0x5c, 0xa3, 0x51, 0xd7, 0xc7,
	0x3b, 0xe8, 0x35, 0xdc, 0xd3, 0x4f, 0x09, 0xea, 0x9b, 0xbc, 0x54, 0xae, 0xe8, 0xe0, 0xd1, 0x96,
	0xbc, 0xb0, 0x7e, 0x01, 0xf6, 0x84, 0xc4, 0x1e, 0x15, 0x74, 0x89, 0x0e, 0x0c, 0xdc, 0x6c, 0x3a,
	0xa8, 0xec, 0xce, 0xb7, 0x11, 0xcb, 0x7e, 0xc5, 0x3b, 0xe8, 0x12, 0xee, 0xff, 0xb4, 0xe2, 0x0b,
	0x7a, 0x77, 0x8b, 0xd7, 0x60, 0x17, 0xef, 0x4d, 0x79, 0xcd, 0xea, 0x13, 0xd4, 0x64, 0xed, 0x40,
	0xd7, 0x78, 0x73, 0x50, 0x1d, 0x6a, 0x70, 0x66, 0xe4, 0x51, 0x7d, 0x9d, 0xf0, 0x0e, 0xfa, 0x4e,
	0x3d, 0xd9, 0x25, 0x19, 0xd7, 0x7b, 0x39, 0xaf, 0xe7, 0x75, 0xc3, 0xd1, 0x1b, 0xe8, 0x1a, 0x84,
	0x8c, 0x06, 0x9b, 0x8d, 0x31, 0xb7, 0xb1, 0xe9, 0x36, 0xa2, 0xe5, 0x39, 0xef, 0x19, 0x2d, 0xaf,
	0xb0, 0xaa, 0xd1, 0xf2, 0x2a, 0x49, 0xe2, 0x1d, 0xf4, 0x0e, 0xba, 0x06, 0xb9, 0x18, 0x59, 0x6c,
	0xd1, 0x61, 0x59, 0x98, 0x1a, 0x16, 0x53, 0xf7, 0x31, 0x88, 0xa4, 0xf4, 0xb4, 0xcd, 0x2e, 0x4d,
	0xf7, 0x79, 0x07, 0x47, 0x15, 0x66, 0x40, 0xe7, 0x9b, 0x55, 0xa9, 0x2e, 0x44, 0x93, 0xa7, 0x2b,
	0x38, 0xd8, 0x58, 0x71, 0x54, 0x3c, 0xb3, 0x75, 0x4c, 0x31, 0x78, 0xd2, 0xa0, 0x35, 0xaa, 0x74,
	0x54, 0x59, 0xf1, 0x32, 0xb3, 0xfa, 0xdd, 0xff, 0x9b, 0x3b, 0x56, 0x76, 0xbb, 0xf4, 0x54, 0xbf,
	0xf4, 0x0d, 0x9e, 0x6e, 0x3b, 0xf2, 0xf8, 0xe5, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0x7e,
	0x62, 0x2d, 0xe3, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppMgrClient is the client API for AppMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppMgrClient interface {
	// Sends request to start a app and list app
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	AppList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error)
	AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error)
	AppLeaderBoard(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppLeaderBoardResponse, error)
	CreateChart(ctx context.Context, in *CreateChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error)
	ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error)
	DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ListNamespace(ctx context.Context, in *ListNamespaceRequest, opts ...grpc.CallOption) (*ListNamespaceResponse, error)
	UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type appMgrClient struct {
	cc *grpc.ClientConn
}

func NewAppMgrClient(cc *grpc.ClientConn) AppMgrClient {
	return &appMgrClient{cc}
}

func (c *appMgrClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/CancelApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/PurgeApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/UpdateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error) {
	out := new(AppOverviewResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/AppOverview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppLeaderBoard(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppLeaderBoardResponse, error) {
	out := new(AppLeaderBoardResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/AppLeaderBoard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CreateChart(ctx context.Context, in *CreateChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/CreateChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error) {
	out := new(ChartListResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/ChartList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error) {
	out := new(ChartDetailResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/ChartDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/DeleteChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ListNamespace(ctx context.Context, in *ListNamespaceRequest, opts ...grpc.CallOption) (*ListNamespaceResponse, error) {
	out := new(ListNamespaceResponse)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/ListNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/UpdateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/appmgr.AppMgr/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMgrServer is the server API for AppMgr service.
type AppMgrServer interface {
	// Sends request to start a app and list app
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	AppList(context.Context, *AppListRequest) (*AppListResponse, error)
	CancelApp(context.Context, *AppID) (*common.Empty, error)
	PurgeApp(context.Context, *AppID) (*common.Empty, error)
	UpdateApp(context.Context, *UpdateAppRequest) (*common.Empty, error)
	AppOverview(context.Context, *common.Empty) (*AppOverviewResponse, error)
	AppLeaderBoard(context.Context, *common.Empty) (*AppLeaderBoardResponse, error)
	CreateChart(context.Context, *CreateChartRequest) (*common.Empty, error)
	ChartList(context.Context, *ChartListRequest) (*ChartListResponse, error)
	ChartDetail(context.Context, *ChartDetailRequest) (*ChartDetailResponse, error)
	DeleteChart(context.Context, *DeleteChartRequest) (*common.Empty, error)
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*common.Empty, error)
	ListNamespace(context.Context, *ListNamespaceRequest) (*ListNamespaceResponse, error)
	UpdateNamespace(context.Context, *UpdateNamespaceRequest) (*common.Empty, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*common.Empty, error)
}

// UnimplementedAppMgrServer can be embedded to have forward compatible implementations.
type UnimplementedAppMgrServer struct {
}

func (*UnimplementedAppMgrServer) CreateApp(ctx context.Context, req *CreateAppRequest) (*CreateAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppList(ctx context.Context, req *AppListRequest) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedAppMgrServer) CancelApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelApp not implemented")
}
func (*UnimplementedAppMgrServer) PurgeApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeApp not implemented")
}
func (*UnimplementedAppMgrServer) UpdateApp(ctx context.Context, req *UpdateAppRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppOverview(ctx context.Context, req *common.Empty) (*AppOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppOverview not implemented")
}
func (*UnimplementedAppMgrServer) AppLeaderBoard(ctx context.Context, req *common.Empty) (*AppLeaderBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppLeaderBoard not implemented")
}
func (*UnimplementedAppMgrServer) CreateChart(ctx context.Context, req *CreateChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChart not implemented")
}
func (*UnimplementedAppMgrServer) ChartList(ctx context.Context, req *ChartListRequest) (*ChartListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartList not implemented")
}
func (*UnimplementedAppMgrServer) ChartDetail(ctx context.Context, req *ChartDetailRequest) (*ChartDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartDetail not implemented")
}
func (*UnimplementedAppMgrServer) DeleteChart(ctx context.Context, req *DeleteChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChart not implemented")
}
func (*UnimplementedAppMgrServer) CreateNamespace(ctx context.Context, req *CreateNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) ListNamespace(ctx context.Context, req *ListNamespaceRequest) (*ListNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespace not implemented")
}
func (*UnimplementedAppMgrServer) UpdateNamespace(ctx context.Context, req *UpdateNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) DeleteNamespace(ctx context.Context, req *DeleteNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}

func RegisterAppMgrServer(s *grpc.Server, srv AppMgrServer) {
	s.RegisterService(&_AppMgr_serviceDesc, srv)
}

func _AppMgr_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppList(ctx, req.(*AppListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CancelApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CancelApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/CancelApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CancelApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_PurgeApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).PurgeApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/PurgeApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).PurgeApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/UpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateApp(ctx, req.(*UpdateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/AppOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppOverview(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppLeaderBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppLeaderBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/AppLeaderBoard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppLeaderBoard(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CreateChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/CreateChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateChart(ctx, req.(*CreateChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/ChartList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartList(ctx, req.(*ChartListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/ChartDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartDetail(ctx, req.(*ChartDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/DeleteChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteChart(ctx, req.(*DeleteChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ListNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ListNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/ListNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ListNamespace(ctx, req.(*ListNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/UpdateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateNamespace(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appmgr.AppMgr/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appmgr.AppMgr",
	HandlerType: (*AppMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApp",
			Handler:    _AppMgr_CreateApp_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _AppMgr_AppList_Handler,
		},
		{
			MethodName: "CancelApp",
			Handler:    _AppMgr_CancelApp_Handler,
		},
		{
			MethodName: "PurgeApp",
			Handler:    _AppMgr_PurgeApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _AppMgr_UpdateApp_Handler,
		},
		{
			MethodName: "AppOverview",
			Handler:    _AppMgr_AppOverview_Handler,
		},
		{
			MethodName: "AppLeaderBoard",
			Handler:    _AppMgr_AppLeaderBoard_Handler,
		},
		{
			MethodName: "CreateChart",
			Handler:    _AppMgr_CreateChart_Handler,
		},
		{
			MethodName: "ChartList",
			Handler:    _AppMgr_ChartList_Handler,
		},
		{
			MethodName: "ChartDetail",
			Handler:    _AppMgr_ChartDetail_Handler,
		},
		{
			MethodName: "DeleteChart",
			Handler:    _AppMgr_DeleteChart_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _AppMgr_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespace",
			Handler:    _AppMgr_ListNamespace_Handler,
		},
		{
			MethodName: "UpdateNamespace",
			Handler:    _AppMgr_UpdateNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _AppMgr_DeleteNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appmgr/v1/grpc/appmgr.proto",
}
