// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskmgr/v1/taskmgr.proto

package gwappmgr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The dccn client request message containing the user's token
type Chart struct {
	ChartName            string   `protobuf:"bytes,1,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartRepo            string   `protobuf:"bytes,2,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,3,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chart) Reset()         { *m = Chart{} }
func (m *Chart) String() string { return proto.CompactTextString(m) }
func (*Chart) ProtoMessage()    {}
func (*Chart) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{0}
}

func (m *Chart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chart.Unmarshal(m, b)
}
func (m *Chart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chart.Marshal(b, m, deterministic)
}
func (m *Chart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chart.Merge(m, src)
}
func (m *Chart) XXX_Size() int {
	return xxx_messageInfo_Chart.Size(m)
}
func (m *Chart) XXX_DiscardUnknown() {
	xxx_messageInfo_Chart.DiscardUnknown(m)
}

var xxx_messageInfo_Chart proto.InternalMessageInfo

func (m *Chart) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *Chart) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *Chart) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

type Namespace struct {
	NsName               string   `protobuf:"bytes,1,opt,name=ns_name,json=nsName,proto3" json:"ns_name,omitempty"`
	NsCpuLimit           uint32   `protobuf:"varint,2,opt,name=ns_cpu_limit,json=nsCpuLimit,proto3" json:"ns_cpu_limit,omitempty"`
	NsMemLimit           uint32   `protobuf:"varint,3,opt,name=ns_mem_limit,json=nsMemLimit,proto3" json:"ns_mem_limit,omitempty"`
	NsStorageLimit       uint32   `protobuf:"varint,4,opt,name=ns_storage_limit,json=nsStorageLimit,proto3" json:"ns_storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{1}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetNsName() string {
	if m != nil {
		return m.NsName
	}
	return ""
}

func (m *Namespace) GetNsCpuLimit() uint32 {
	if m != nil {
		return m.NsCpuLimit
	}
	return 0
}

func (m *Namespace) GetNsMemLimit() uint32 {
	if m != nil {
		return m.NsMemLimit
	}
	return 0
}

func (m *Namespace) GetNsStorageLimit() uint32 {
	if m != nil {
		return m.NsStorageLimit
	}
	return 0
}

type CreateAppRequest struct {
	AppName              string     `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Chart                *Chart     `protobuf:"bytes,2,opt,name=chart,proto3" json:"chart,omitempty"`
	NsId                 string     `protobuf:"bytes,3,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	Namespace            *Namespace `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{2}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CreateAppRequest) GetChart() *Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *CreateAppRequest) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

func (m *CreateAppRequest) GetNamespace() *Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type CreateAppResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{3}
}

func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(m, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppListResponse struct {
	AppReports           []*common.AppReport `protobuf:"bytes,1,rep,name=app_reports,json=appReports,proto3" json:"app_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{4}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetAppReports() []*common.AppReport {
	if m != nil {
		return m.AppReports
	}
	return nil
}

type AppDetailResponse struct {
	AppReport            *common.AppReport `protobuf:"bytes,1,opt,name=app_report,json=appReport,proto3" json:"app_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppDetailResponse) Reset()         { *m = AppDetailResponse{} }
func (m *AppDetailResponse) String() string { return proto.CompactTextString(m) }
func (*AppDetailResponse) ProtoMessage()    {}
func (*AppDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{5}
}

func (m *AppDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppDetailResponse.Unmarshal(m, b)
}
func (m *AppDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppDetailResponse.Marshal(b, m, deterministic)
}
func (m *AppDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppDetailResponse.Merge(m, src)
}
func (m *AppDetailResponse) XXX_Size() int {
	return xxx_messageInfo_AppDetailResponse.Size(m)
}
func (m *AppDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppDetailResponse proto.InternalMessageInfo

func (m *AppDetailResponse) GetAppReport() *common.AppReport {
	if m != nil {
		return m.AppReport
	}
	return nil
}

type AppID struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppID) Reset()         { *m = AppID{} }
func (m *AppID) String() string { return proto.CompactTextString(m) }
func (*AppID) ProtoMessage()    {}
func (*AppID) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{6}
}

func (m *AppID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppID.Unmarshal(m, b)
}
func (m *AppID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppID.Marshal(b, m, deterministic)
}
func (m *AppID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppID.Merge(m, src)
}
func (m *AppID) XXX_Size() int {
	return xxx_messageInfo_AppID.Size(m)
}
func (m *AppID) XXX_DiscardUnknown() {
	xxx_messageInfo_AppID.DiscardUnknown(m)
}

var xxx_messageInfo_AppID proto.InternalMessageInfo

func (m *AppID) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type UpdateAppRequest struct {
	AppName              string   `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ChartVer             string   `protobuf:"bytes,5,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{7}
}

func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *UpdateAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UpdateAppRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

type AppCountRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ClusterId            string   `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppCountRequest) Reset()         { *m = AppCountRequest{} }
func (m *AppCountRequest) String() string { return proto.CompactTextString(m) }
func (*AppCountRequest) ProtoMessage()    {}
func (*AppCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{8}
}

func (m *AppCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppCountRequest.Unmarshal(m, b)
}
func (m *AppCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppCountRequest.Marshal(b, m, deterministic)
}
func (m *AppCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCountRequest.Merge(m, src)
}
func (m *AppCountRequest) XXX_Size() int {
	return xxx_messageInfo_AppCountRequest.Size(m)
}
func (m *AppCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppCountRequest proto.InternalMessageInfo

func (m *AppCountRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AppCountRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type AppCountResponse struct {
	AppCount             uint32   `protobuf:"varint,1,opt,name=app_count,json=appCount,proto3" json:"app_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppCountResponse) Reset()         { *m = AppCountResponse{} }
func (m *AppCountResponse) String() string { return proto.CompactTextString(m) }
func (*AppCountResponse) ProtoMessage()    {}
func (*AppCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{9}
}

func (m *AppCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppCountResponse.Unmarshal(m, b)
}
func (m *AppCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppCountResponse.Marshal(b, m, deterministic)
}
func (m *AppCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCountResponse.Merge(m, src)
}
func (m *AppCountResponse) XXX_Size() int {
	return xxx_messageInfo_AppCountResponse.Size(m)
}
func (m *AppCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppCountResponse proto.InternalMessageInfo

func (m *AppCountResponse) GetAppCount() uint32 {
	if m != nil {
		return m.AppCount
	}
	return 0
}

type AppOverviewResponse struct {
	ClusterCount         uint32   `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	NamespaceCount       uint32   `protobuf:"varint,2,opt,name=namespace_count,json=namespaceCount,proto3" json:"namespace_count,omitempty"`
	NetworkCount         uint32   `protobuf:"varint,3,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	TotalAppCount        uint32   `protobuf:"varint,4,opt,name=total_app_count,json=totalAppCount,proto3" json:"total_app_count,omitempty"`
	CpuTotal             float32  `protobuf:"fixed32,5,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUsage             float32  `protobuf:"fixed32,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemTotal             float32  `protobuf:"fixed32,7,opt,name=mem_total,json=memTotal,proto3" json:"mem_total,omitempty"`
	MemUsage             float32  `protobuf:"fixed32,8,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	StorageTotal         float32  `protobuf:"fixed32,9,opt,name=storage_total,json=storageTotal,proto3" json:"storage_total,omitempty"`
	StorageUsage         float32  `protobuf:"fixed32,10,opt,name=storage_usage,json=storageUsage,proto3" json:"storage_usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppOverviewResponse) Reset()         { *m = AppOverviewResponse{} }
func (m *AppOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*AppOverviewResponse) ProtoMessage()    {}
func (*AppOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{10}
}

func (m *AppOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppOverviewResponse.Unmarshal(m, b)
}
func (m *AppOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppOverviewResponse.Marshal(b, m, deterministic)
}
func (m *AppOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppOverviewResponse.Merge(m, src)
}
func (m *AppOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_AppOverviewResponse.Size(m)
}
func (m *AppOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppOverviewResponse proto.InternalMessageInfo

func (m *AppOverviewResponse) GetClusterCount() uint32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *AppOverviewResponse) GetNamespaceCount() uint32 {
	if m != nil {
		return m.NamespaceCount
	}
	return 0
}

func (m *AppOverviewResponse) GetNetworkCount() uint32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

func (m *AppOverviewResponse) GetTotalAppCount() uint32 {
	if m != nil {
		return m.TotalAppCount
	}
	return 0
}

func (m *AppOverviewResponse) GetCpuTotal() float32 {
	if m != nil {
		return m.CpuTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetCpuUsage() float32 {
	if m != nil {
		return m.CpuUsage
	}
	return 0
}

func (m *AppOverviewResponse) GetMemTotal() float32 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetMemUsage() float32 {
	if m != nil {
		return m.MemUsage
	}
	return 0
}

func (m *AppOverviewResponse) GetStorageTotal() float32 {
	if m != nil {
		return m.StorageTotal
	}
	return 0
}

func (m *AppOverviewResponse) GetStorageUsage() float32 {
	if m != nil {
		return m.StorageUsage
	}
	return 0
}

type UploadChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartFile            []byte   `protobuf:"bytes,4,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadChartRequest) Reset()         { *m = UploadChartRequest{} }
func (m *UploadChartRequest) String() string { return proto.CompactTextString(m) }
func (*UploadChartRequest) ProtoMessage()    {}
func (*UploadChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{11}
}

func (m *UploadChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadChartRequest.Unmarshal(m, b)
}
func (m *UploadChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadChartRequest.Marshal(b, m, deterministic)
}
func (m *UploadChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadChartRequest.Merge(m, src)
}
func (m *UploadChartRequest) XXX_Size() int {
	return xxx_messageInfo_UploadChartRequest.Size(m)
}
func (m *UploadChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadChartRequest proto.InternalMessageInfo

func (m *UploadChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *UploadChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *UploadChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *UploadChartRequest) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type ChartListRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartListRequest) Reset()         { *m = ChartListRequest{} }
func (m *ChartListRequest) String() string { return proto.CompactTextString(m) }
func (*ChartListRequest) ProtoMessage()    {}
func (*ChartListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{12}
}

func (m *ChartListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListRequest.Unmarshal(m, b)
}
func (m *ChartListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListRequest.Marshal(b, m, deterministic)
}
func (m *ChartListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListRequest.Merge(m, src)
}
func (m *ChartListRequest) XXX_Size() int {
	return xxx_messageInfo_ChartListRequest.Size(m)
}
func (m *ChartListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListRequest proto.InternalMessageInfo

func (m *ChartListRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

type ChartListResponse struct {
	Charts               []*common.Chart `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChartListResponse) Reset()         { *m = ChartListResponse{} }
func (m *ChartListResponse) String() string { return proto.CompactTextString(m) }
func (*ChartListResponse) ProtoMessage()    {}
func (*ChartListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{13}
}

func (m *ChartListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListResponse.Unmarshal(m, b)
}
func (m *ChartListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListResponse.Marshal(b, m, deterministic)
}
func (m *ChartListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListResponse.Merge(m, src)
}
func (m *ChartListResponse) XXX_Size() int {
	return xxx_messageInfo_ChartListResponse.Size(m)
}
func (m *ChartListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListResponse proto.InternalMessageInfo

func (m *ChartListResponse) GetCharts() []*common.Chart {
	if m != nil {
		return m.Charts
	}
	return nil
}

type ChartDetailRequest struct {
	ChartName            string   `protobuf:"bytes,1,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartRepo            string   `protobuf:"bytes,2,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,3,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartDetailRequest) Reset()         { *m = ChartDetailRequest{} }
func (m *ChartDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ChartDetailRequest) ProtoMessage()    {}
func (*ChartDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{14}
}

func (m *ChartDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailRequest.Unmarshal(m, b)
}
func (m *ChartDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailRequest.Marshal(b, m, deterministic)
}
func (m *ChartDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailRequest.Merge(m, src)
}
func (m *ChartDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ChartDetailRequest.Size(m)
}
func (m *ChartDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailRequest proto.InternalMessageInfo

func (m *ChartDetailRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *ChartDetailRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *ChartDetailRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

type ChartDetailResponse struct {
	ChartName            string                       `protobuf:"bytes,1,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartRepo            string                       `protobuf:"bytes,2,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVersionDetails  []*common.ChartVersionDetail `protobuf:"bytes,3,rep,name=chart_version_details,json=chartVersionDetails,proto3" json:"chart_version_details,omitempty"`
	ReadmeMd             string                       `protobuf:"bytes,4,opt,name=readme_md,json=readmeMd,proto3" json:"readme_md,omitempty"`
	ValuesYaml           string                       `protobuf:"bytes,5,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ChartDetailResponse) Reset()         { *m = ChartDetailResponse{} }
func (m *ChartDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ChartDetailResponse) ProtoMessage()    {}
func (*ChartDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{15}
}

func (m *ChartDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailResponse.Unmarshal(m, b)
}
func (m *ChartDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailResponse.Marshal(b, m, deterministic)
}
func (m *ChartDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailResponse.Merge(m, src)
}
func (m *ChartDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ChartDetailResponse.Size(m)
}
func (m *ChartDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailResponse proto.InternalMessageInfo

func (m *ChartDetailResponse) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *ChartDetailResponse) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *ChartDetailResponse) GetChartVersionDetails() []*common.ChartVersionDetail {
	if m != nil {
		return m.ChartVersionDetails
	}
	return nil
}

func (m *ChartDetailResponse) GetReadmeMd() string {
	if m != nil {
		return m.ReadmeMd
	}
	return ""
}

func (m *ChartDetailResponse) GetValuesYaml() string {
	if m != nil {
		return m.ValuesYaml
	}
	return ""
}

type DeleteChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteChartRequest) Reset()         { *m = DeleteChartRequest{} }
func (m *DeleteChartRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChartRequest) ProtoMessage()    {}
func (*DeleteChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{16}
}

func (m *DeleteChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteChartRequest.Unmarshal(m, b)
}
func (m *DeleteChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteChartRequest.Marshal(b, m, deterministic)
}
func (m *DeleteChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteChartRequest.Merge(m, src)
}
func (m *DeleteChartRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteChartRequest.Size(m)
}
func (m *DeleteChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteChartRequest proto.InternalMessageInfo

func (m *DeleteChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DeleteChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DeleteChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type CreateNamespaceRequest struct {
	NsName               string   `protobuf:"bytes,2,opt,name=ns_name,json=nsName,proto3" json:"ns_name,omitempty"`
	NsCpuLimit           uint32   `protobuf:"varint,6,opt,name=ns_cpu_limit,json=nsCpuLimit,proto3" json:"ns_cpu_limit,omitempty"`
	NsMemLimit           uint32   `protobuf:"varint,7,opt,name=ns_mem_limit,json=nsMemLimit,proto3" json:"ns_mem_limit,omitempty"`
	NsStorageLimit       uint32   `protobuf:"varint,8,opt,name=ns_storage_limit,json=nsStorageLimit,proto3" json:"ns_storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{17}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetNsName() string {
	if m != nil {
		return m.NsName
	}
	return ""
}

func (m *CreateNamespaceRequest) GetNsCpuLimit() uint32 {
	if m != nil {
		return m.NsCpuLimit
	}
	return 0
}

func (m *CreateNamespaceRequest) GetNsMemLimit() uint32 {
	if m != nil {
		return m.NsMemLimit
	}
	return 0
}

func (m *CreateNamespaceRequest) GetNsStorageLimit() uint32 {
	if m != nil {
		return m.NsStorageLimit
	}
	return 0
}

type CreateNamespaceResponse struct {
	NsId                 string   `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{18}
}

func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(m, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

func (m *CreateNamespaceResponse) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

type NamespaceListResponse struct {
	NsReports            []*common.NamespaceReport `protobuf:"bytes,1,rep,name=ns_reports,json=nsReports,proto3" json:"ns_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NamespaceListResponse) Reset()         { *m = NamespaceListResponse{} }
func (m *NamespaceListResponse) String() string { return proto.CompactTextString(m) }
func (*NamespaceListResponse) ProtoMessage()    {}
func (*NamespaceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{19}
}

func (m *NamespaceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceListResponse.Unmarshal(m, b)
}
func (m *NamespaceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceListResponse.Marshal(b, m, deterministic)
}
func (m *NamespaceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceListResponse.Merge(m, src)
}
func (m *NamespaceListResponse) XXX_Size() int {
	return xxx_messageInfo_NamespaceListResponse.Size(m)
}
func (m *NamespaceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceListResponse proto.InternalMessageInfo

func (m *NamespaceListResponse) GetNsReports() []*common.NamespaceReport {
	if m != nil {
		return m.NsReports
	}
	return nil
}

type UpdateNamespaceRequest struct {
	NsCpuLimit           uint32   `protobuf:"varint,1,opt,name=ns_cpu_limit,json=nsCpuLimit,proto3" json:"ns_cpu_limit,omitempty"`
	NsMemLimit           uint32   `protobuf:"varint,2,opt,name=ns_mem_limit,json=nsMemLimit,proto3" json:"ns_mem_limit,omitempty"`
	NsStorageLimit       uint32   `protobuf:"varint,3,opt,name=ns_storage_limit,json=nsStorageLimit,proto3" json:"ns_storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{20}
}

func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(m, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

func (m *UpdateNamespaceRequest) GetNsCpuLimit() uint32 {
	if m != nil {
		return m.NsCpuLimit
	}
	return 0
}

func (m *UpdateNamespaceRequest) GetNsMemLimit() uint32 {
	if m != nil {
		return m.NsMemLimit
	}
	return 0
}

func (m *UpdateNamespaceRequest) GetNsStorageLimit() uint32 {
	if m != nil {
		return m.NsStorageLimit
	}
	return 0
}

type DeleteNamespaceRequest struct {
	NsId                 string   `protobuf:"bytes,1,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{21}
}

func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

type DownloadChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartRequest) Reset()         { *m = DownloadChartRequest{} }
func (m *DownloadChartRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadChartRequest) ProtoMessage()    {}
func (*DownloadChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{22}
}

func (m *DownloadChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartRequest.Unmarshal(m, b)
}
func (m *DownloadChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartRequest.Marshal(b, m, deterministic)
}
func (m *DownloadChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartRequest.Merge(m, src)
}
func (m *DownloadChartRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadChartRequest.Size(m)
}
func (m *DownloadChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartRequest proto.InternalMessageInfo

func (m *DownloadChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DownloadChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DownloadChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type DownloadChartResponse struct {
	ChartFile            []byte   `protobuf:"bytes,1,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartResponse) Reset()         { *m = DownloadChartResponse{} }
func (m *DownloadChartResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadChartResponse) ProtoMessage()    {}
func (*DownloadChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{23}
}

func (m *DownloadChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartResponse.Unmarshal(m, b)
}
func (m *DownloadChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartResponse.Marshal(b, m, deterministic)
}
func (m *DownloadChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartResponse.Merge(m, src)
}
func (m *DownloadChartResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadChartResponse.Size(m)
}
func (m *DownloadChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartResponse proto.InternalMessageInfo

func (m *DownloadChartResponse) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type Source struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{24}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *Source) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *Source) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type Destination struct {
	SaveasVer            string   `protobuf:"bytes,1,opt,name=saveas_ver,json=saveasVer,proto3" json:"saveas_ver,omitempty"`
	SaveasName           string   `protobuf:"bytes,2,opt,name=saveas_name,json=saveasName,proto3" json:"saveas_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{25}
}

func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (m *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(m, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetSaveasVer() string {
	if m != nil {
		return m.SaveasVer
	}
	return ""
}

func (m *Destination) GetSaveasName() string {
	if m != nil {
		return m.SaveasName
	}
	return ""
}

type SaveAsChartRequest struct {
	Source               *Source      `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *Destination `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	ValuesYaml           []byte       `protobuf:"bytes,3,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SaveAsChartRequest) Reset()         { *m = SaveAsChartRequest{} }
func (m *SaveAsChartRequest) String() string { return proto.CompactTextString(m) }
func (*SaveAsChartRequest) ProtoMessage()    {}
func (*SaveAsChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{26}
}

func (m *SaveAsChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAsChartRequest.Unmarshal(m, b)
}
func (m *SaveAsChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAsChartRequest.Marshal(b, m, deterministic)
}
func (m *SaveAsChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAsChartRequest.Merge(m, src)
}
func (m *SaveAsChartRequest) XXX_Size() int {
	return xxx_messageInfo_SaveAsChartRequest.Size(m)
}
func (m *SaveAsChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAsChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAsChartRequest proto.InternalMessageInfo

func (m *SaveAsChartRequest) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *SaveAsChartRequest) GetDestination() *Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *SaveAsChartRequest) GetValuesYaml() []byte {
	if m != nil {
		return m.ValuesYaml
	}
	return nil
}

func init() {
	proto.RegisterType((*Chart)(nil), "gwappmgr.Chart")
	proto.RegisterType((*Namespace)(nil), "gwappmgr.Namespace")
	proto.RegisterType((*CreateAppRequest)(nil), "gwappmgr.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "gwappmgr.CreateAppResponse")
	proto.RegisterType((*AppListResponse)(nil), "gwappmgr.AppListResponse")
	proto.RegisterType((*AppDetailResponse)(nil), "gwappmgr.AppDetailResponse")
	proto.RegisterType((*AppID)(nil), "gwappmgr.AppID")
	proto.RegisterType((*UpdateAppRequest)(nil), "gwappmgr.UpdateAppRequest")
	proto.RegisterType((*AppCountRequest)(nil), "gwappmgr.AppCountRequest")
	proto.RegisterType((*AppCountResponse)(nil), "gwappmgr.AppCountResponse")
	proto.RegisterType((*AppOverviewResponse)(nil), "gwappmgr.AppOverviewResponse")
	proto.RegisterType((*UploadChartRequest)(nil), "gwappmgr.UploadChartRequest")
	proto.RegisterType((*ChartListRequest)(nil), "gwappmgr.ChartListRequest")
	proto.RegisterType((*ChartListResponse)(nil), "gwappmgr.ChartListResponse")
	proto.RegisterType((*ChartDetailRequest)(nil), "gwappmgr.ChartDetailRequest")
	proto.RegisterType((*ChartDetailResponse)(nil), "gwappmgr.ChartDetailResponse")
	proto.RegisterType((*DeleteChartRequest)(nil), "gwappmgr.DeleteChartRequest")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "gwappmgr.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "gwappmgr.CreateNamespaceResponse")
	proto.RegisterType((*NamespaceListResponse)(nil), "gwappmgr.NamespaceListResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "gwappmgr.UpdateNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "gwappmgr.DeleteNamespaceRequest")
	proto.RegisterType((*DownloadChartRequest)(nil), "gwappmgr.DownloadChartRequest")
	proto.RegisterType((*DownloadChartResponse)(nil), "gwappmgr.DownloadChartResponse")
	proto.RegisterType((*Source)(nil), "gwappmgr.Source")
	proto.RegisterType((*Destination)(nil), "gwappmgr.Destination")
	proto.RegisterType((*SaveAsChartRequest)(nil), "gwappmgr.SaveAsChartRequest")
}

func init() { proto.RegisterFile("taskmgr/v1/taskmgr.proto", fileDescriptor_dbc0cfcc64f892be) }

var fileDescriptor_dbc0cfcc64f892be = []byte{
	// 1513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xd7, 0xda, 0x8d, 0x63, 0xbf, 0x8d, 0xb1, 0x33, 0x6e, 0x12, 0xc7, 0x69, 0x9b, 0x74, 0x2b,
	0x20, 0x0a, 0x22, 0x56, 0x53, 0x51, 0x2a, 0x40, 0x88, 0x90, 0x80, 0x14, 0xb5, 0x01, 0xe4, 0x36,
	0x2d, 0x45, 0x80, 0x35, 0xb5, 0xa7, 0xc6, 0xaa, 0x77, 0x77, 0xba, 0xb3, 0xeb, 0xa8, 0xaa, 0x2a,
	0x21, 0x0e, 0x70, 0xe3, 0x00, 0x17, 0x0e, 0x48, 0x7c, 0x28, 0xbe, 0x02, 0x12, 0x37, 0x2e, 0x7c,
	0x01, 0x34, 0x6f, 0x66, 0x77, 0x67, 0xd7, 0xdb, 0xd4, 0x12, 0xd0, 0x53, 0xbc, 0xef, 0xcf, 0xef,
	0xfd, 0x99, 0x99, 0xf7, 0x7e, 0x81, 0x76, 0x48, 0xc5, 0x23, 0x77, 0x14, 0x74, 0xa7, 0x57, 0xbb,
	0xfa, 0xe7, 0x2e, 0x0f, 0xfc, 0xd0, 0x27, 0xd5, 0xd1, 0x29, 0xe5, 0xdc, 0x1d, 0x05, 0x9d, 0x0b,
	0x23, 0xdf, 0x1f, 0x4d, 0x58, 0x97, 0xf2, 0x71, 0x97, 0x7a, 0x9e, 0x1f, 0xd2, 0x70, 0xec, 0x7b,
	0x42, 0xd9, 0x75, 0x5a, 0x03, 0xdf, 0x75, 0x7d, 0xaf, 0xab, 0xfe, 0x28, 0xa1, 0xf3, 0x00, 0x16,
	0x0e, 0xbe, 0xa1, 0x41, 0x48, 0x2e, 0x02, 0x0c, 0xe4, 0x8f, 0xbe, 0x47, 0x5d, 0xd6, 0xb6, 0xb6,
	0xac, 0xed, 0x5a, 0xaf, 0x86, 0x92, 0x4f, 0xa8, 0xcb, 0x52, 0x75, 0xc0, 0xb8, 0xdf, 0x2e, 0x19,
	0xea, 0x1e, 0xe3, 0x3e, 0xd9, 0x00, 0xf5, 0xd1, 0x9f, 0xb2, 0xa0, 0x5d, 0x46, 0x6d, 0x15, 0x05,
	0x77, 0x59, 0xe0, 0xfc, 0x64, 0x41, 0x4d, 0x82, 0x08, 0x4e, 0x07, 0x8c, 0xac, 0xc1, 0xa2, 0x27,
	0xcc, 0x28, 0x15, 0x4f, 0x60, 0x88, 0x2d, 0x58, 0xf2, 0x44, 0x7f, 0xc0, 0xa3, 0xfe, 0x64, 0xec,
	0x8e, 0x43, 0x0c, 0x52, 0xef, 0x81, 0x27, 0x0e, 0x78, 0x74, 0x4b, 0x4a, 0xb4, 0x85, 0xcb, 0x5c,
	0x6d, 0x51, 0x8e, 0x2d, 0x8e, 0x99, 0xab, 0x2c, 0xb6, 0xa1, 0xe9, 0x89, 0xbe, 0x08, 0xfd, 0x80,
	0x8e, 0x98, 0xb6, 0x3a, 0x87, 0x56, 0xaf, 0x78, 0xe2, 0xb6, 0x12, 0xa3, 0xa5, 0xf3, 0xab, 0x05,
	0xcd, 0x83, 0x80, 0xd1, 0x90, 0xed, 0x73, 0xde, 0x63, 0x8f, 0x23, 0x26, 0x42, 0xb2, 0x0e, 0x55,
	0xca, 0xb9, 0x99, 0xdc, 0x22, 0xe5, 0x1c, 0xb3, 0x7b, 0x15, 0x16, 0xb0, 0x20, 0x4c, 0xcb, 0xde,
	0x6b, 0xec, 0xc6, 0x5d, 0xdf, 0xc5, 0xfe, 0xf5, 0x94, 0x96, 0xb4, 0x60, 0xc1, 0x13, 0xfd, 0xf1,
	0x50, 0x37, 0xe1, 0x9c, 0x27, 0x8e, 0x86, 0xe4, 0x2a, 0xd4, 0xbc, 0xb8, 0x7e, 0x4c, 0xc7, 0xde,
	0x6b, 0xa5, 0xfe, 0x49, 0x6b, 0x7a, 0xa9, 0x95, 0xb3, 0x03, 0xcb, 0x46, 0x76, 0x82, 0xfb, 0x9e,
	0x60, 0x64, 0x05, 0x2a, 0x32, 0xbd, 0xf1, 0x50, 0x27, 0xb7, 0x40, 0x39, 0x3f, 0x1a, 0x3a, 0x37,
	0xa1, 0xb1, 0xcf, 0xf9, 0xad, 0xb1, 0x08, 0x13, 0xcb, 0x1b, 0x60, 0x4b, 0x4b, 0x79, 0x58, 0x41,
	0x28, 0xda, 0xd6, 0x56, 0x79, 0xdb, 0xde, 0x5b, 0xdb, 0x35, 0x8f, 0x7e, 0x17, 0x91, 0xa5, 0xbe,
	0x07, 0x34, 0xfe, 0x29, 0x9c, 0x9b, 0xb0, 0xbc, 0xcf, 0xf9, 0x21, 0x0b, 0xe9, 0x78, 0x92, 0xc0,
	0x5d, 0x07, 0x48, 0xe1, 0x30, 0xf8, 0x19, 0x68, 0xb5, 0x04, 0xcd, 0xb9, 0x04, 0x0b, 0xfb, 0x9c,
	0x1f, 0x1d, 0x3e, 0x2f, 0x73, 0x0a, 0xcd, 0x13, 0x3e, 0x9c, 0xfb, 0x0c, 0x52, 0x94, 0x92, 0x81,
	0x92, 0xbd, 0x7c, 0x0b, 0xb9, 0xcb, 0xf7, 0x21, 0x36, 0xe7, 0xc0, 0x8f, 0xbc, 0x30, 0x8e, 0xd0,
	0x84, 0x72, 0x94, 0x64, 0x22, 0x7f, 0xe2, 0xed, 0x9e, 0x44, 0x22, 0x64, 0x41, 0x0a, 0x5e, 0xd3,
	0x92, 0xa3, 0xa1, 0xd3, 0x85, 0x66, 0x8a, 0xa1, 0x5b, 0xb2, 0x01, 0xb2, 0xce, 0xfe, 0x40, 0x0a,
	0x11, 0xaa, 0xde, 0x93, 0x79, 0xa3, 0x91, 0xf3, 0x57, 0x09, 0x5a, 0xfb, 0x9c, 0x7f, 0x3a, 0x65,
	0xc1, 0x74, 0xcc, 0x4e, 0x13, 0xa7, 0x2b, 0x50, 0x8f, 0xe3, 0x98, 0x8e, 0x4b, 0x5a, 0x88, 0xce,
	0xe4, 0x75, 0x68, 0x24, 0xf7, 0x40, 0x9b, 0x95, 0xf4, 0x15, 0x8e, 0xc5, 0xca, 0xf0, 0x0a, 0xd4,
	0x3d, 0x16, 0x9e, 0xfa, 0xc1, 0x23, 0x6d, 0xa6, 0xde, 0xc3, 0x92, 0x16, 0x2a, 0xa3, 0xd7, 0xa0,
	0x11, 0xfa, 0x21, 0x9d, 0xf4, 0xd3, 0x6c, 0xd5, 0x83, 0xa8, 0xa3, 0x38, 0xae, 0x0b, 0x9b, 0xc8,
	0xa3, 0x3e, 0x0a, 0xb1, 0x89, 0xa5, 0x5e, 0x75, 0xc0, 0xa3, 0x3b, 0xf2, 0x3b, 0x56, 0x46, 0x82,
	0x8e, 0x58, 0xbb, 0x92, 0x28, 0x4f, 0xe4, 0xb7, 0x54, 0xca, 0x27, 0xa9, 0x3c, 0x17, 0x95, 0xd2,
	0x65, 0x6e, 0xe2, 0x29, 0x95, 0xca, 0xb3, 0x9a, 0x28, 0x95, 0xe7, 0x15, 0xa8, 0xc7, 0x4f, 0x55,
	0x79, 0xd7, 0xd0, 0x60, 0x49, 0x0b, 0x15, 0x82, 0x61, 0xa4, 0x50, 0x20, 0x63, 0x84, 0x48, 0xce,
	0x8f, 0x16, 0x90, 0x13, 0x3e, 0xf1, 0xe9, 0x50, 0xbd, 0x46, 0x7d, 0xd2, 0xd9, 0xa9, 0x65, 0x9d,
	0x39, 0xb5, 0x4a, 0xd9, 0x8b, 0x93, 0x1b, 0x88, 0xe5, 0xe7, 0x0e, 0xc4, 0x87, 0xe3, 0x89, 0x7a,
	0xd4, 0x4b, 0x5a, 0xfd, 0xf1, 0x78, 0xc2, 0x9c, 0xab, 0xd0, 0xc4, 0x4c, 0xd4, 0xab, 0x9c, 0x27,
	0x1b, 0xe7, 0x03, 0x58, 0x36, 0x5c, 0xf4, 0x8d, 0x79, 0x03, 0x2a, 0x68, 0x11, 0xbf, 0xe1, 0x56,
	0xf6, 0xd5, 0xa9, 0x6a, 0xb5, 0x89, 0xe3, 0x03, 0x41, 0x41, 0xfc, 0x7a, 0x73, 0x61, 0xff, 0xfb,
	0xc9, 0xfe, 0xa7, 0x05, 0xad, 0x4c, 0x44, 0x9d, 0xf5, 0xbf, 0x0b, 0x79, 0x07, 0x56, 0x92, 0x90,
	0x62, 0xec, 0x7b, 0xfd, 0x21, 0xa2, 0x8b, 0x76, 0x19, 0x5b, 0xb0, 0x55, 0xd0, 0x82, 0xbb, 0xca,
	0x52, 0xa7, 0xd1, 0x1a, 0xcc, 0xc8, 0x84, 0x2c, 0x24, 0x60, 0x74, 0xe8, 0xb2, 0xbe, 0x3b, 0xc4,
	0xf3, 0xaa, 0xf5, 0xaa, 0x4a, 0x70, 0x3c, 0x24, 0x9b, 0x60, 0x4f, 0xe9, 0x24, 0x62, 0xa2, 0xff,
	0x84, 0xba, 0x13, 0x3d, 0x44, 0x40, 0x89, 0xee, 0x53, 0x77, 0x22, 0x5b, 0x7b, 0xc8, 0x26, 0x2c,
	0x64, 0x2f, 0xe9, 0x7e, 0x39, 0xbf, 0x59, 0xb0, 0xaa, 0x36, 0x40, 0xba, 0x1f, 0x74, 0x54, 0x63,
	0x83, 0x96, 0xce, 0xdc, 0xa0, 0x95, 0x17, 0x6e, 0xd0, 0xc5, 0xb9, 0x36, 0x68, 0xb5, 0x70, 0x83,
	0xee, 0xc2, 0xda, 0x4c, 0x82, 0xfa, 0xfc, 0x93, 0x2d, 0x68, 0xa5, 0x5b, 0xd0, 0x39, 0x81, 0x95,
	0xc4, 0x32, 0x73, 0xc7, 0xdf, 0x03, 0xf0, 0x44, 0x6e, 0x57, 0x5d, 0xcc, 0x1e, 0xb2, 0x11, 0x42,
	0xed, 0x18, 0x4f, 0xc4, 0x0b, 0xeb, 0x7b, 0x0b, 0x56, 0xd5, 0x12, 0x99, 0x69, 0x54, 0xbe, 0x1f,
	0xd6, 0x0b, 0xfb, 0x51, 0x9a, 0xab, 0x1f, 0xe5, 0xc2, 0x7e, 0xbc, 0x09, 0xab, 0xea, 0x8a, 0xcc,
	0xe4, 0x51, 0xd8, 0x8e, 0xc7, 0x70, 0xfe, 0xd0, 0x3f, 0xf5, 0x5e, 0xe2, 0xcc, 0x72, 0xae, 0xc3,
	0x4a, 0x2e, 0x64, 0xfe, 0xbd, 0xe2, 0x30, 0xb3, 0xf2, 0xc3, 0x6c, 0x00, 0x95, 0xdb, 0x7e, 0x14,
	0x0c, 0xd8, 0xff, 0x99, 0xdc, 0x31, 0xd8, 0x87, 0x4c, 0x84, 0x63, 0x0f, 0x49, 0xab, 0xb4, 0x16,
	0x74, 0xca, 0xa8, 0x40, 0x2c, 0x1d, 0x49, 0x49, 0x24, 0xd8, 0x26, 0xd8, 0x5a, 0x6d, 0xbc, 0x03,
	0xed, 0x81, 0x70, 0xbf, 0x58, 0x40, 0x6e, 0xd3, 0x29, 0xdb, 0x17, 0x99, 0xee, 0x6e, 0x43, 0x45,
	0x60, 0x29, 0x9a, 0xc5, 0x34, 0x53, 0x1e, 0xa6, 0x4a, 0xec, 0x69, 0x3d, 0x79, 0x1b, 0xec, 0x61,
	0x9a, 0x8f, 0xa6, 0x7d, 0x2b, 0xa9, 0xb9, 0x91, 0x6c, 0xcf, 0xb4, 0xcc, 0xcf, 0x92, 0x32, 0x76,
	0xd3, 0x98, 0x25, 0x7b, 0x7f, 0xd7, 0xa1, 0xb2, 0xcf, 0xf9, 0xf1, 0x28, 0x20, 0x5f, 0x42, 0x2d,
	0xa1, 0x79, 0xa4, 0x63, 0x70, 0xca, 0x1c, 0x33, 0xed, 0x6c, 0x14, 0xea, 0xd4, 0xf1, 0x39, 0xab,
	0xdf, 0xfd, 0xfe, 0xc7, 0xcf, 0xa5, 0xa6, 0x63, 0x77, 0x29, 0xe7, 0xdd, 0x01, 0xea, 0xdf, 0xb1,
	0x76, 0xc8, 0x2d, 0x58, 0xd4, 0xc4, 0x90, 0xe4, 0xf6, 0xc6, 0x47, 0x2e, 0x0f, 0x9f, 0x74, 0xd6,
	0x53, 0xd0, 0x1c, 0x81, 0x74, 0x96, 0x11, 0xd2, 0x26, 0x35, 0x84, 0x9c, 0x48, 0x88, 0x7b, 0x50,
	0x4b, 0x98, 0x21, 0x69, 0x64, 0x5c, 0x8f, 0x0e, 0xcd, 0x04, 0x67, 0xf8, 0xa3, 0x73, 0x01, 0xd1,
	0x56, 0xc9, 0x79, 0x44, 0x53, 0xe3, 0xbc, 0xfb, 0x54, 0x71, 0xb9, 0x67, 0xa4, 0x07, 0xb5, 0x03,
	0xea, 0x0d, 0x98, 0x24, 0x23, 0xb3, 0xc0, 0x45, 0x99, 0x3b, 0x9b, 0x08, 0xb8, 0xee, 0x28, 0xc0,
	0x01, 0x7a, 0x27, 0x80, 0xb2, 0xf4, 0x63, 0xa8, 0x7e, 0x16, 0x05, 0x23, 0x36, 0x3f, 0xe4, 0x06,
	0x42, 0xae, 0xec, 0xb4, 0x10, 0x92, 0x4b, 0xe7, 0x34, 0xc5, 0xaf, 0xa0, 0x96, 0x10, 0x55, 0xf3,
	0x9c, 0xf2, 0xec, 0x75, 0x9e, 0x6c, 0x23, 0xf4, 0xc9, 0x64, 0x7b, 0x02, 0xd5, 0x84, 0x88, 0x65,
	0x0f, 0xc5, 0x24, 0xae, 0x9d, 0x4e, 0x91, 0x4a, 0xb7, 0x98, 0x60, 0x8c, 0x25, 0x02, 0xaa, 0x23,
	0x08, 0xf5, 0x39, 0xd8, 0x06, 0x0b, 0x2d, 0xbe, 0x03, 0x17, 0x33, 0x98, 0x79, 0xc6, 0xea, 0xac,
	0x20, 0x6c, 0x83, 0xd4, 0x11, 0xd6, 0x8f, 0xa1, 0xbe, 0xb5, 0xc0, 0x36, 0xf8, 0x16, 0xb9, 0x60,
	0xb6, 0x24, 0x3f, 0xd2, 0x8a, 0x9b, 0xf2, 0x3e, 0x22, 0xdf, 0x70, 0xae, 0x75, 0x71, 0x06, 0x74,
	0x23, 0xf4, 0xeb, 0x3e, 0x4d, 0xe7, 0xcb, 0xb3, 0xf8, 0x43, 0x3e, 0xf1, 0xe4, 0x63, 0xca, 0x02,
	0xec, 0xd9, 0x7d, 0xa8, 0x25, 0x74, 0x29, 0xf3, 0x74, 0x72, 0xb4, 0x2b, 0xf3, 0x74, 0xf2, 0xfc,
	0xca, 0x69, 0x61, 0x16, 0x75, 0x62, 0xeb, 0x2c, 0xf0, 0xa6, 0xff, 0x60, 0x81, 0x6d, 0xd0, 0x1a,
	0xb3, 0xba, 0x59, 0x7e, 0x65, 0x76, 0xb0, 0x80, 0x0b, 0x39, 0xef, 0x62, 0x84, 0xb7, 0x48, 0x5c,
	0x67, 0x7c, 0xfb, 0xe7, 0xa9, 0x93, 0xdc, 0x93, 0x43, 0x31, 0xa1, 0x1d, 0x66, 0x22, 0xb3, 0x6c,
	0xa4, 0xb8, 0xcd, 0xfa, 0x00, 0x77, 0xea, 0x49, 0x78, 0xe9, 0x47, 0xbe, 0x00, 0xdb, 0x98, 0x8e,
	0x26, 0xf0, 0xec, 0xd0, 0x2c, 0x06, 0x6e, 0x23, 0x30, 0xe9, 0xc4, 0xc0, 0x6a, 0xf6, 0xca, 0x93,
	0x19, 0x43, 0x3d, 0xb3, 0x66, 0xc8, 0x25, 0x23, 0xed, 0x82, 0x95, 0xd7, 0xd9, 0x7c, 0xae, 0x5e,
	0xf7, 0x70, 0x0d, 0x63, 0x2d, 0x93, 0x46, 0x5c, 0x84, 0xb6, 0x22, 0x21, 0x34, 0x72, 0x1c, 0x84,
	0x6c, 0xe5, 0x27, 0x65, 0x7e, 0x1d, 0x77, 0x2e, 0x9f, 0x61, 0x91, 0x1d, 0x58, 0xce, 0x72, 0x37,
	0xf9, 0x9f, 0xcb, 0x98, 0xab, 0x5f, 0x43, 0x3d, 0xc3, 0x64, 0x8a, 0x5f, 0xd6, 0x66, 0xc1, 0xbf,
	0xf8, 0x99, 0xbb, 0x97, 0x56, 0x95, 0x06, 0xc1, 0xfb, 0xf7, 0x10, 0x1a, 0x39, 0x46, 0x63, 0x56,
	0x55, 0x4c, 0x76, 0x8a, 0x0f, 0xa9, 0xa8, 0x0e, 0x35, 0x7f, 0x64, 0x1d, 0x8f, 0xa0, 0x91, 0x63,
	0x2c, 0x66, 0x9c, 0x62, 0x32, 0x53, 0x1c, 0xe7, 0x32, 0xc6, 0xd9, 0xd8, 0x59, 0x37, 0xe2, 0xa8,
	0x9b, 0xd6, 0x7d, 0x8a, 0xd4, 0xe7, 0xd9, 0x83, 0x0a, 0xda, 0x5f, 0xfb, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x34, 0x09, 0x42, 0xcd, 0xc9, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppMgrClient is the client API for AppMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppMgrClient interface {
	// Sends request to start a app and list app
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	AppList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppListResponse, error)
	AppDetail(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*AppDetailResponse, error)
	CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error)
	AppCount(ctx context.Context, in *AppCountRequest, opts ...grpc.CallOption) (*AppCountResponse, error)
	AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error)
	UploadChart(ctx context.Context, in *UploadChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error)
	ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error)
	DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	SaveAsChart(ctx context.Context, in *SaveAsChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DownloadChart(ctx context.Context, in *DownloadChartRequest, opts ...grpc.CallOption) (*DownloadChartResponse, error)
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	NamespaceList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error)
	UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type appMgrClient struct {
	cc *grpc.ClientConn
}

func NewAppMgrClient(cc *grpc.ClientConn) AppMgrClient {
	return &appMgrClient{cc}
}

func (c *appMgrClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppDetail(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*AppDetailResponse, error) {
	out := new(AppDetailResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CancelApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/PurgeApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/UpdateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppCount(ctx context.Context, in *AppCountRequest, opts ...grpc.CallOption) (*AppCountResponse, error) {
	out := new(AppCountResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error) {
	out := new(AppOverviewResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppOverview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UploadChart(ctx context.Context, in *UploadChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/UploadChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error) {
	out := new(ChartListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/ChartList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error) {
	out := new(ChartDetailResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/ChartDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DeleteChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) SaveAsChart(ctx context.Context, in *SaveAsChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/SaveAsChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DownloadChart(ctx context.Context, in *DownloadChartRequest, opts ...grpc.CallOption) (*DownloadChartResponse, error) {
	out := new(DownloadChartResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DownloadChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) NamespaceList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error) {
	out := new(NamespaceListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/NamespaceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/UpdateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMgrServer is the server API for AppMgr service.
type AppMgrServer interface {
	// Sends request to start a app and list app
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	AppList(context.Context, *common.Empty) (*AppListResponse, error)
	AppDetail(context.Context, *AppID) (*AppDetailResponse, error)
	CancelApp(context.Context, *AppID) (*common.Empty, error)
	PurgeApp(context.Context, *AppID) (*common.Empty, error)
	UpdateApp(context.Context, *UpdateAppRequest) (*common.Empty, error)
	AppCount(context.Context, *AppCountRequest) (*AppCountResponse, error)
	AppOverview(context.Context, *common.Empty) (*AppOverviewResponse, error)
	UploadChart(context.Context, *UploadChartRequest) (*common.Empty, error)
	ChartList(context.Context, *ChartListRequest) (*ChartListResponse, error)
	ChartDetail(context.Context, *ChartDetailRequest) (*ChartDetailResponse, error)
	DeleteChart(context.Context, *DeleteChartRequest) (*common.Empty, error)
	SaveAsChart(context.Context, *SaveAsChartRequest) (*common.Empty, error)
	DownloadChart(context.Context, *DownloadChartRequest) (*DownloadChartResponse, error)
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	NamespaceList(context.Context, *common.Empty) (*NamespaceListResponse, error)
	UpdateNamespace(context.Context, *UpdateNamespaceRequest) (*common.Empty, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*common.Empty, error)
}

// UnimplementedAppMgrServer can be embedded to have forward compatible implementations.
type UnimplementedAppMgrServer struct {
}

func (*UnimplementedAppMgrServer) CreateApp(ctx context.Context, req *CreateAppRequest) (*CreateAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppList(ctx context.Context, req *common.Empty) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedAppMgrServer) AppDetail(ctx context.Context, req *AppID) (*AppDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppDetail not implemented")
}
func (*UnimplementedAppMgrServer) CancelApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelApp not implemented")
}
func (*UnimplementedAppMgrServer) PurgeApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeApp not implemented")
}
func (*UnimplementedAppMgrServer) UpdateApp(ctx context.Context, req *UpdateAppRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppCount(ctx context.Context, req *AppCountRequest) (*AppCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppCount not implemented")
}
func (*UnimplementedAppMgrServer) AppOverview(ctx context.Context, req *common.Empty) (*AppOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppOverview not implemented")
}
func (*UnimplementedAppMgrServer) UploadChart(ctx context.Context, req *UploadChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadChart not implemented")
}
func (*UnimplementedAppMgrServer) ChartList(ctx context.Context, req *ChartListRequest) (*ChartListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartList not implemented")
}
func (*UnimplementedAppMgrServer) ChartDetail(ctx context.Context, req *ChartDetailRequest) (*ChartDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartDetail not implemented")
}
func (*UnimplementedAppMgrServer) DeleteChart(ctx context.Context, req *DeleteChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChart not implemented")
}
func (*UnimplementedAppMgrServer) SaveAsChart(ctx context.Context, req *SaveAsChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAsChart not implemented")
}
func (*UnimplementedAppMgrServer) DownloadChart(ctx context.Context, req *DownloadChartRequest) (*DownloadChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadChart not implemented")
}
func (*UnimplementedAppMgrServer) CreateNamespace(ctx context.Context, req *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) NamespaceList(ctx context.Context, req *common.Empty) (*NamespaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NamespaceList not implemented")
}
func (*UnimplementedAppMgrServer) UpdateNamespace(ctx context.Context, req *UpdateNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) DeleteNamespace(ctx context.Context, req *DeleteNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}

func RegisterAppMgrServer(s *grpc.Server, srv AppMgrServer) {
	s.RegisterService(&_AppMgr_serviceDesc, srv)
}

func _AppMgr_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppDetail(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CancelApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CancelApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CancelApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CancelApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_PurgeApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).PurgeApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/PurgeApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).PurgeApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/UpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateApp(ctx, req.(*UpdateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppCount(ctx, req.(*AppCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppOverview(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UploadChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UploadChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/UploadChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UploadChart(ctx, req.(*UploadChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/ChartList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartList(ctx, req.(*ChartListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/ChartDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartDetail(ctx, req.(*ChartDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DeleteChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteChart(ctx, req.(*DeleteChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_SaveAsChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAsChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).SaveAsChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/SaveAsChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).SaveAsChart(ctx, req.(*SaveAsChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DownloadChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DownloadChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DownloadChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DownloadChart(ctx, req.(*DownloadChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_NamespaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).NamespaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/NamespaceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).NamespaceList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/UpdateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateNamespace(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwappmgr.AppMgr",
	HandlerType: (*AppMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApp",
			Handler:    _AppMgr_CreateApp_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _AppMgr_AppList_Handler,
		},
		{
			MethodName: "AppDetail",
			Handler:    _AppMgr_AppDetail_Handler,
		},
		{
			MethodName: "CancelApp",
			Handler:    _AppMgr_CancelApp_Handler,
		},
		{
			MethodName: "PurgeApp",
			Handler:    _AppMgr_PurgeApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _AppMgr_UpdateApp_Handler,
		},
		{
			MethodName: "AppCount",
			Handler:    _AppMgr_AppCount_Handler,
		},
		{
			MethodName: "AppOverview",
			Handler:    _AppMgr_AppOverview_Handler,
		},
		{
			MethodName: "UploadChart",
			Handler:    _AppMgr_UploadChart_Handler,
		},
		{
			MethodName: "ChartList",
			Handler:    _AppMgr_ChartList_Handler,
		},
		{
			MethodName: "ChartDetail",
			Handler:    _AppMgr_ChartDetail_Handler,
		},
		{
			MethodName: "DeleteChart",
			Handler:    _AppMgr_DeleteChart_Handler,
		},
		{
			MethodName: "SaveAsChart",
			Handler:    _AppMgr_SaveAsChart_Handler,
		},
		{
			MethodName: "DownloadChart",
			Handler:    _AppMgr_DownloadChart_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _AppMgr_CreateNamespace_Handler,
		},
		{
			MethodName: "NamespaceList",
			Handler:    _AppMgr_NamespaceList_Handler,
		},
		{
			MethodName: "UpdateNamespace",
			Handler:    _AppMgr_UpdateNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _AppMgr_DeleteNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskmgr/v1/taskmgr.proto",
}
