// Code generated by protoc-gen-go. DO NOT EDIT.
// source: taskmgr/v1/taskmgr.proto

package gwappmgr

import (
	context "context"
	fmt "fmt"
	common "github.com/Ankr-network/dccn-common/protos/common"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The dccn client request message containing the user's token
type CreateAppRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Chartname            string   `protobuf:"bytes,3,opt,name=chartname,proto3" json:"chartname,omitempty"`
	Chartrepo            string   `protobuf:"bytes,4,opt,name=chartrepo,proto3" json:"chartrepo,omitempty"`
	Chartversion         string   `protobuf:"bytes,5,opt,name=chartversion,proto3" json:"chartversion,omitempty"`
	Chartappversion      string   `protobuf:"bytes,6,opt,name=chartappversion,proto3" json:"chartappversion,omitempty"`
	NamespaceId          string   `protobuf:"bytes,7,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	NsId                 string   `protobuf:"bytes,8,opt,name=ns_id,json=nsId,proto3" json:"ns_id,omitempty"`
	NsName               string   `protobuf:"bytes,9,opt,name=ns_name,json=nsName,proto3" json:"ns_name,omitempty"`
	NsClusterId          string   `protobuf:"bytes,10,opt,name=ns_cluster_id,json=nsClusterId,proto3" json:"ns_cluster_id,omitempty"`
	NsClusterName        string   `protobuf:"bytes,11,opt,name=ns_cluster_name,json=nsClusterName,proto3" json:"ns_cluster_name,omitempty"`
	NsCpuLimit           uint64   `protobuf:"varint,12,opt,name=ns_cpu_limit,json=nsCpuLimit,proto3" json:"ns_cpu_limit,omitempty"`
	NsMemLimit           uint64   `protobuf:"varint,13,opt,name=ns_mem_limit,json=nsMemLimit,proto3" json:"ns_mem_limit,omitempty"`
	NsStorageLimit       uint64   `protobuf:"varint,14,opt,name=ns_storage_limit,json=nsStorageLimit,proto3" json:"ns_storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppRequest) Reset()         { *m = CreateAppRequest{} }
func (m *CreateAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequest) ProtoMessage()    {}
func (*CreateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{0}
}

func (m *CreateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequest.Unmarshal(m, b)
}
func (m *CreateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequest.Merge(m, src)
}
func (m *CreateAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequest.Size(m)
}
func (m *CreateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequest proto.InternalMessageInfo

func (m *CreateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAppRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateAppRequest) GetChartname() string {
	if m != nil {
		return m.Chartname
	}
	return ""
}

func (m *CreateAppRequest) GetChartrepo() string {
	if m != nil {
		return m.Chartrepo
	}
	return ""
}

func (m *CreateAppRequest) GetChartversion() string {
	if m != nil {
		return m.Chartversion
	}
	return ""
}

func (m *CreateAppRequest) GetChartappversion() string {
	if m != nil {
		return m.Chartappversion
	}
	return ""
}

func (m *CreateAppRequest) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *CreateAppRequest) GetNsId() string {
	if m != nil {
		return m.NsId
	}
	return ""
}

func (m *CreateAppRequest) GetNsName() string {
	if m != nil {
		return m.NsName
	}
	return ""
}

func (m *CreateAppRequest) GetNsClusterId() string {
	if m != nil {
		return m.NsClusterId
	}
	return ""
}

func (m *CreateAppRequest) GetNsClusterName() string {
	if m != nil {
		return m.NsClusterName
	}
	return ""
}

func (m *CreateAppRequest) GetNsCpuLimit() uint64 {
	if m != nil {
		return m.NsCpuLimit
	}
	return 0
}

func (m *CreateAppRequest) GetNsMemLimit() uint64 {
	if m != nil {
		return m.NsMemLimit
	}
	return 0
}

func (m *CreateAppRequest) GetNsStorageLimit() uint64 {
	if m != nil {
		return m.NsStorageLimit
	}
	return 0
}

type CreateAppResponse struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAppResponse) Reset()         { *m = CreateAppResponse{} }
func (m *CreateAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAppResponse) ProtoMessage()    {}
func (*CreateAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{1}
}

func (m *CreateAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResponse.Unmarshal(m, b)
}
func (m *CreateAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResponse.Merge(m, src)
}
func (m *CreateAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAppResponse.Size(m)
}
func (m *CreateAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResponse proto.InternalMessageInfo

func (m *CreateAppResponse) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type AppListResponse struct {
	AppReports           []*common.AppReport `protobuf:"bytes,1,rep,name=app_reports,json=appReports,proto3" json:"app_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AppListResponse) Reset()         { *m = AppListResponse{} }
func (m *AppListResponse) String() string { return proto.CompactTextString(m) }
func (*AppListResponse) ProtoMessage()    {}
func (*AppListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{2}
}

func (m *AppListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppListResponse.Unmarshal(m, b)
}
func (m *AppListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppListResponse.Marshal(b, m, deterministic)
}
func (m *AppListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppListResponse.Merge(m, src)
}
func (m *AppListResponse) XXX_Size() int {
	return xxx_messageInfo_AppListResponse.Size(m)
}
func (m *AppListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppListResponse proto.InternalMessageInfo

func (m *AppListResponse) GetAppReports() []*common.AppReport {
	if m != nil {
		return m.AppReports
	}
	return nil
}

type AppDetailResponse struct {
	AppReport            *common.AppReport `protobuf:"bytes,1,opt,name=app_report,json=appReport,proto3" json:"app_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppDetailResponse) Reset()         { *m = AppDetailResponse{} }
func (m *AppDetailResponse) String() string { return proto.CompactTextString(m) }
func (*AppDetailResponse) ProtoMessage()    {}
func (*AppDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{3}
}

func (m *AppDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppDetailResponse.Unmarshal(m, b)
}
func (m *AppDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppDetailResponse.Marshal(b, m, deterministic)
}
func (m *AppDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppDetailResponse.Merge(m, src)
}
func (m *AppDetailResponse) XXX_Size() int {
	return xxx_messageInfo_AppDetailResponse.Size(m)
}
func (m *AppDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppDetailResponse proto.InternalMessageInfo

func (m *AppDetailResponse) GetAppReport() *common.AppReport {
	if m != nil {
		return m.AppReport
	}
	return nil
}

type AppID struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppID) Reset()         { *m = AppID{} }
func (m *AppID) String() string { return proto.CompactTextString(m) }
func (*AppID) ProtoMessage()    {}
func (*AppID) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{4}
}

func (m *AppID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppID.Unmarshal(m, b)
}
func (m *AppID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppID.Marshal(b, m, deterministic)
}
func (m *AppID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppID.Merge(m, src)
}
func (m *AppID) XXX_Size() int {
	return xxx_messageInfo_AppID.Size(m)
}
func (m *AppID) XXX_DiscardUnknown() {
	xxx_messageInfo_AppID.DiscardUnknown(m)
}

var xxx_messageInfo_AppID proto.InternalMessageInfo

func (m *AppID) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

type UpdateAppRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AppId                string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Chartname            string   `protobuf:"bytes,3,opt,name=chartname,proto3" json:"chartname,omitempty"`
	Chartrepo            string   `protobuf:"bytes,4,opt,name=chartrepo,proto3" json:"chartrepo,omitempty"`
	Chartversion         string   `protobuf:"bytes,5,opt,name=chartversion,proto3" json:"chartversion,omitempty"`
	Chartappversion      string   `protobuf:"bytes,6,opt,name=chartappversion,proto3" json:"chartappversion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAppRequest) Reset()         { *m = UpdateAppRequest{} }
func (m *UpdateAppRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAppRequest) ProtoMessage()    {}
func (*UpdateAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{5}
}

func (m *UpdateAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppRequest.Unmarshal(m, b)
}
func (m *UpdateAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppRequest.Merge(m, src)
}
func (m *UpdateAppRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAppRequest.Size(m)
}
func (m *UpdateAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppRequest proto.InternalMessageInfo

func (m *UpdateAppRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateAppRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UpdateAppRequest) GetChartname() string {
	if m != nil {
		return m.Chartname
	}
	return ""
}

func (m *UpdateAppRequest) GetChartrepo() string {
	if m != nil {
		return m.Chartrepo
	}
	return ""
}

func (m *UpdateAppRequest) GetChartversion() string {
	if m != nil {
		return m.Chartversion
	}
	return ""
}

func (m *UpdateAppRequest) GetChartappversion() string {
	if m != nil {
		return m.Chartappversion
	}
	return ""
}

type AppOverviewResponse struct {
	ClusterCount         int32    `protobuf:"varint,1,opt,name=cluster_count,json=clusterCount,proto3" json:"cluster_count,omitempty"`
	EnvironmentCount     int32    `protobuf:"varint,2,opt,name=environment_count,json=environmentCount,proto3" json:"environment_count,omitempty"`
	RegionCount          int32    `protobuf:"varint,3,opt,name=region_count,json=regionCount,proto3" json:"region_count,omitempty"`
	TotalAppCount        int32    `protobuf:"varint,4,opt,name=total_app_count,json=totalAppCount,proto3" json:"total_app_count,omitempty"`
	HealthAppCount       int32    `protobuf:"varint,5,opt,name=health_app_count,json=healthAppCount,proto3" json:"health_app_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppOverviewResponse) Reset()         { *m = AppOverviewResponse{} }
func (m *AppOverviewResponse) String() string { return proto.CompactTextString(m) }
func (*AppOverviewResponse) ProtoMessage()    {}
func (*AppOverviewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{6}
}

func (m *AppOverviewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppOverviewResponse.Unmarshal(m, b)
}
func (m *AppOverviewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppOverviewResponse.Marshal(b, m, deterministic)
}
func (m *AppOverviewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppOverviewResponse.Merge(m, src)
}
func (m *AppOverviewResponse) XXX_Size() int {
	return xxx_messageInfo_AppOverviewResponse.Size(m)
}
func (m *AppOverviewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppOverviewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppOverviewResponse proto.InternalMessageInfo

func (m *AppOverviewResponse) GetClusterCount() int32 {
	if m != nil {
		return m.ClusterCount
	}
	return 0
}

func (m *AppOverviewResponse) GetEnvironmentCount() int32 {
	if m != nil {
		return m.EnvironmentCount
	}
	return 0
}

func (m *AppOverviewResponse) GetRegionCount() int32 {
	if m != nil {
		return m.RegionCount
	}
	return 0
}

func (m *AppOverviewResponse) GetTotalAppCount() int32 {
	if m != nil {
		return m.TotalAppCount
	}
	return 0
}

func (m *AppOverviewResponse) GetHealthAppCount() int32 {
	if m != nil {
		return m.HealthAppCount
	}
	return 0
}

type AppLeaderBoardResponse struct {
	List                 []*AppLeaderBoardDetail `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AppLeaderBoardResponse) Reset()         { *m = AppLeaderBoardResponse{} }
func (m *AppLeaderBoardResponse) String() string { return proto.CompactTextString(m) }
func (*AppLeaderBoardResponse) ProtoMessage()    {}
func (*AppLeaderBoardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{7}
}

func (m *AppLeaderBoardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLeaderBoardResponse.Unmarshal(m, b)
}
func (m *AppLeaderBoardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLeaderBoardResponse.Marshal(b, m, deterministic)
}
func (m *AppLeaderBoardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLeaderBoardResponse.Merge(m, src)
}
func (m *AppLeaderBoardResponse) XXX_Size() int {
	return xxx_messageInfo_AppLeaderBoardResponse.Size(m)
}
func (m *AppLeaderBoardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLeaderBoardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppLeaderBoardResponse proto.InternalMessageInfo

func (m *AppLeaderBoardResponse) GetList() []*AppLeaderBoardDetail {
	if m != nil {
		return m.List
	}
	return nil
}

type AppLeaderBoardDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Number               float64  `protobuf:"fixed64,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppLeaderBoardDetail) Reset()         { *m = AppLeaderBoardDetail{} }
func (m *AppLeaderBoardDetail) String() string { return proto.CompactTextString(m) }
func (*AppLeaderBoardDetail) ProtoMessage()    {}
func (*AppLeaderBoardDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{8}
}

func (m *AppLeaderBoardDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppLeaderBoardDetail.Unmarshal(m, b)
}
func (m *AppLeaderBoardDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppLeaderBoardDetail.Marshal(b, m, deterministic)
}
func (m *AppLeaderBoardDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppLeaderBoardDetail.Merge(m, src)
}
func (m *AppLeaderBoardDetail) XXX_Size() int {
	return xxx_messageInfo_AppLeaderBoardDetail.Size(m)
}
func (m *AppLeaderBoardDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_AppLeaderBoardDetail.DiscardUnknown(m)
}

var xxx_messageInfo_AppLeaderBoardDetail proto.InternalMessageInfo

func (m *AppLeaderBoardDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppLeaderBoardDetail) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CreateChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	ChartFile            []byte   `protobuf:"bytes,4,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChartRequest) Reset()         { *m = CreateChartRequest{} }
func (m *CreateChartRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChartRequest) ProtoMessage()    {}
func (*CreateChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{9}
}

func (m *CreateChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChartRequest.Unmarshal(m, b)
}
func (m *CreateChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChartRequest.Marshal(b, m, deterministic)
}
func (m *CreateChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChartRequest.Merge(m, src)
}
func (m *CreateChartRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChartRequest.Size(m)
}
func (m *CreateChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChartRequest proto.InternalMessageInfo

func (m *CreateChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *CreateChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *CreateChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *CreateChartRequest) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type ChartListRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChartListRequest) Reset()         { *m = ChartListRequest{} }
func (m *ChartListRequest) String() string { return proto.CompactTextString(m) }
func (*ChartListRequest) ProtoMessage()    {}
func (*ChartListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{10}
}

func (m *ChartListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListRequest.Unmarshal(m, b)
}
func (m *ChartListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListRequest.Marshal(b, m, deterministic)
}
func (m *ChartListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListRequest.Merge(m, src)
}
func (m *ChartListRequest) XXX_Size() int {
	return xxx_messageInfo_ChartListRequest.Size(m)
}
func (m *ChartListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListRequest proto.InternalMessageInfo

func (m *ChartListRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

type ChartListResponse struct {
	Charts               []*common.Chart `protobuf:"bytes,1,rep,name=charts,proto3" json:"charts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChartListResponse) Reset()         { *m = ChartListResponse{} }
func (m *ChartListResponse) String() string { return proto.CompactTextString(m) }
func (*ChartListResponse) ProtoMessage()    {}
func (*ChartListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{11}
}

func (m *ChartListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartListResponse.Unmarshal(m, b)
}
func (m *ChartListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartListResponse.Marshal(b, m, deterministic)
}
func (m *ChartListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartListResponse.Merge(m, src)
}
func (m *ChartListResponse) XXX_Size() int {
	return xxx_messageInfo_ChartListResponse.Size(m)
}
func (m *ChartListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartListResponse proto.InternalMessageInfo

func (m *ChartListResponse) GetCharts() []*common.Chart {
	if m != nil {
		return m.Charts
	}
	return nil
}

type ChartDetailRequest struct {
	Chart                *common.Chart `protobuf:"bytes,1,opt,name=chart,proto3" json:"chart,omitempty"`
	ShowVersion          string        `protobuf:"bytes,2,opt,name=show_version,json=showVersion,proto3" json:"show_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ChartDetailRequest) Reset()         { *m = ChartDetailRequest{} }
func (m *ChartDetailRequest) String() string { return proto.CompactTextString(m) }
func (*ChartDetailRequest) ProtoMessage()    {}
func (*ChartDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{12}
}

func (m *ChartDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailRequest.Unmarshal(m, b)
}
func (m *ChartDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailRequest.Marshal(b, m, deterministic)
}
func (m *ChartDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailRequest.Merge(m, src)
}
func (m *ChartDetailRequest) XXX_Size() int {
	return xxx_messageInfo_ChartDetailRequest.Size(m)
}
func (m *ChartDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailRequest proto.InternalMessageInfo

func (m *ChartDetailRequest) GetChart() *common.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *ChartDetailRequest) GetShowVersion() string {
	if m != nil {
		return m.ShowVersion
	}
	return ""
}

type ChartDetailResponse struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repo                 string                  `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Versiondetails       []*common.VersionDetail `protobuf:"bytes,3,rep,name=versiondetails,proto3" json:"versiondetails,omitempty"`
	ReadmeMd             string                  `protobuf:"bytes,4,opt,name=readme_md,json=readmeMd,proto3" json:"readme_md,omitempty"`
	ValuesYaml           string                  `protobuf:"bytes,5,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ChartDetailResponse) Reset()         { *m = ChartDetailResponse{} }
func (m *ChartDetailResponse) String() string { return proto.CompactTextString(m) }
func (*ChartDetailResponse) ProtoMessage()    {}
func (*ChartDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{13}
}

func (m *ChartDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChartDetailResponse.Unmarshal(m, b)
}
func (m *ChartDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChartDetailResponse.Marshal(b, m, deterministic)
}
func (m *ChartDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChartDetailResponse.Merge(m, src)
}
func (m *ChartDetailResponse) XXX_Size() int {
	return xxx_messageInfo_ChartDetailResponse.Size(m)
}
func (m *ChartDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChartDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChartDetailResponse proto.InternalMessageInfo

func (m *ChartDetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChartDetailResponse) GetRepo() string {
	if m != nil {
		return m.Repo
	}
	return ""
}

func (m *ChartDetailResponse) GetVersiondetails() []*common.VersionDetail {
	if m != nil {
		return m.Versiondetails
	}
	return nil
}

func (m *ChartDetailResponse) GetReadmeMd() string {
	if m != nil {
		return m.ReadmeMd
	}
	return ""
}

func (m *ChartDetailResponse) GetValuesYaml() string {
	if m != nil {
		return m.ValuesYaml
	}
	return ""
}

type DeleteChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteChartRequest) Reset()         { *m = DeleteChartRequest{} }
func (m *DeleteChartRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteChartRequest) ProtoMessage()    {}
func (*DeleteChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{14}
}

func (m *DeleteChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteChartRequest.Unmarshal(m, b)
}
func (m *DeleteChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteChartRequest.Marshal(b, m, deterministic)
}
func (m *DeleteChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteChartRequest.Merge(m, src)
}
func (m *DeleteChartRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteChartRequest.Size(m)
}
func (m *DeleteChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteChartRequest proto.InternalMessageInfo

func (m *DeleteChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DeleteChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DeleteChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type CreateNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClusterId            string   `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName          string   `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	CreationDate         uint64   `protobuf:"varint,5,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	CpuLimit             uint64   `protobuf:"varint,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemLimit             uint64   `protobuf:"varint,7,opt,name=mem_limit,json=memLimit,proto3" json:"mem_limit,omitempty"`
	StorageLimit         uint64   `protobuf:"varint,8,opt,name=storage_limit,json=storageLimit,proto3" json:"storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{15}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateNamespaceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateNamespaceRequest) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *CreateNamespaceRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *CreateNamespaceRequest) GetCreationDate() uint64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *CreateNamespaceRequest) GetCpuLimit() uint64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *CreateNamespaceRequest) GetMemLimit() uint64 {
	if m != nil {
		return m.MemLimit
	}
	return 0
}

func (m *CreateNamespaceRequest) GetStorageLimit() uint64 {
	if m != nil {
		return m.StorageLimit
	}
	return 0
}

type CreateNamespaceResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespaceResponse) Reset()         { *m = CreateNamespaceResponse{} }
func (m *CreateNamespaceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceResponse) ProtoMessage()    {}
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{16}
}

func (m *CreateNamespaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceResponse.Unmarshal(m, b)
}
func (m *CreateNamespaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceResponse.Merge(m, src)
}
func (m *CreateNamespaceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceResponse.Size(m)
}
func (m *CreateNamespaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceResponse proto.InternalMessageInfo

func (m *CreateNamespaceResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NamespaceListResponse struct {
	NamespaceReports     []*common.NamespaceReport `protobuf:"bytes,1,rep,name=namespace_reports,json=namespaceReports,proto3" json:"namespace_reports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NamespaceListResponse) Reset()         { *m = NamespaceListResponse{} }
func (m *NamespaceListResponse) String() string { return proto.CompactTextString(m) }
func (*NamespaceListResponse) ProtoMessage()    {}
func (*NamespaceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{17}
}

func (m *NamespaceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceListResponse.Unmarshal(m, b)
}
func (m *NamespaceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceListResponse.Marshal(b, m, deterministic)
}
func (m *NamespaceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceListResponse.Merge(m, src)
}
func (m *NamespaceListResponse) XXX_Size() int {
	return xxx_messageInfo_NamespaceListResponse.Size(m)
}
func (m *NamespaceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceListResponse proto.InternalMessageInfo

func (m *NamespaceListResponse) GetNamespaceReports() []*common.NamespaceReport {
	if m != nil {
		return m.NamespaceReports
	}
	return nil
}

type UpdateNamespaceRequest struct {
	CpuLimit             uint64   `protobuf:"varint,1,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemLimit             uint64   `protobuf:"varint,2,opt,name=mem_limit,json=memLimit,proto3" json:"mem_limit,omitempty"`
	StorageLimit         uint64   `protobuf:"varint,3,opt,name=storage_limit,json=storageLimit,proto3" json:"storage_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNamespaceRequest) Reset()         { *m = UpdateNamespaceRequest{} }
func (m *UpdateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNamespaceRequest) ProtoMessage()    {}
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{18}
}

func (m *UpdateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNamespaceRequest.Unmarshal(m, b)
}
func (m *UpdateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNamespaceRequest.Merge(m, src)
}
func (m *UpdateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNamespaceRequest.Size(m)
}
func (m *UpdateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNamespaceRequest proto.InternalMessageInfo

func (m *UpdateNamespaceRequest) GetCpuLimit() uint64 {
	if m != nil {
		return m.CpuLimit
	}
	return 0
}

func (m *UpdateNamespaceRequest) GetMemLimit() uint64 {
	if m != nil {
		return m.MemLimit
	}
	return 0
}

func (m *UpdateNamespaceRequest) GetStorageLimit() uint64 {
	if m != nil {
		return m.StorageLimit
	}
	return 0
}

type DeleteNamespaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNamespaceRequest) Reset()         { *m = DeleteNamespaceRequest{} }
func (m *DeleteNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNamespaceRequest) ProtoMessage()    {}
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{19}
}

func (m *DeleteNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNamespaceRequest.Unmarshal(m, b)
}
func (m *DeleteNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNamespaceRequest.Merge(m, src)
}
func (m *DeleteNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNamespaceRequest.Size(m)
}
func (m *DeleteNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNamespaceRequest proto.InternalMessageInfo

func (m *DeleteNamespaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DownloadChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartRequest) Reset()         { *m = DownloadChartRequest{} }
func (m *DownloadChartRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadChartRequest) ProtoMessage()    {}
func (*DownloadChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{20}
}

func (m *DownloadChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartRequest.Unmarshal(m, b)
}
func (m *DownloadChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartRequest.Marshal(b, m, deterministic)
}
func (m *DownloadChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartRequest.Merge(m, src)
}
func (m *DownloadChartRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadChartRequest.Size(m)
}
func (m *DownloadChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartRequest proto.InternalMessageInfo

func (m *DownloadChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *DownloadChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *DownloadChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

type DownloadChartResponse struct {
	ChartFile            []byte   `protobuf:"bytes,1,opt,name=chart_file,json=chartFile,proto3" json:"chart_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadChartResponse) Reset()         { *m = DownloadChartResponse{} }
func (m *DownloadChartResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadChartResponse) ProtoMessage()    {}
func (*DownloadChartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{21}
}

func (m *DownloadChartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadChartResponse.Unmarshal(m, b)
}
func (m *DownloadChartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadChartResponse.Marshal(b, m, deterministic)
}
func (m *DownloadChartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadChartResponse.Merge(m, src)
}
func (m *DownloadChartResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadChartResponse.Size(m)
}
func (m *DownloadChartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadChartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadChartResponse proto.InternalMessageInfo

func (m *DownloadChartResponse) GetChartFile() []byte {
	if m != nil {
		return m.ChartFile
	}
	return nil
}

type SaveAsChartRequest struct {
	ChartRepo            string   `protobuf:"bytes,1,opt,name=chart_repo,json=chartRepo,proto3" json:"chart_repo,omitempty"`
	ChartVer             string   `protobuf:"bytes,2,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	ChartName            string   `protobuf:"bytes,3,opt,name=chart_name,json=chartName,proto3" json:"chart_name,omitempty"`
	SaveasVer            string   `protobuf:"bytes,4,opt,name=saveas_ver,json=saveasVer,proto3" json:"saveas_ver,omitempty"`
	SaveasName           string   `protobuf:"bytes,5,opt,name=saveas_name,json=saveasName,proto3" json:"saveas_name,omitempty"`
	ValuesYaml           []byte   `protobuf:"bytes,6,opt,name=values_yaml,json=valuesYaml,proto3" json:"values_yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveAsChartRequest) Reset()         { *m = SaveAsChartRequest{} }
func (m *SaveAsChartRequest) String() string { return proto.CompactTextString(m) }
func (*SaveAsChartRequest) ProtoMessage()    {}
func (*SaveAsChartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc0cfcc64f892be, []int{22}
}

func (m *SaveAsChartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveAsChartRequest.Unmarshal(m, b)
}
func (m *SaveAsChartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveAsChartRequest.Marshal(b, m, deterministic)
}
func (m *SaveAsChartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveAsChartRequest.Merge(m, src)
}
func (m *SaveAsChartRequest) XXX_Size() int {
	return xxx_messageInfo_SaveAsChartRequest.Size(m)
}
func (m *SaveAsChartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveAsChartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveAsChartRequest proto.InternalMessageInfo

func (m *SaveAsChartRequest) GetChartRepo() string {
	if m != nil {
		return m.ChartRepo
	}
	return ""
}

func (m *SaveAsChartRequest) GetChartVer() string {
	if m != nil {
		return m.ChartVer
	}
	return ""
}

func (m *SaveAsChartRequest) GetChartName() string {
	if m != nil {
		return m.ChartName
	}
	return ""
}

func (m *SaveAsChartRequest) GetSaveasVer() string {
	if m != nil {
		return m.SaveasVer
	}
	return ""
}

func (m *SaveAsChartRequest) GetSaveasName() string {
	if m != nil {
		return m.SaveasName
	}
	return ""
}

func (m *SaveAsChartRequest) GetValuesYaml() []byte {
	if m != nil {
		return m.ValuesYaml
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAppRequest)(nil), "gwappmgr.CreateAppRequest")
	proto.RegisterType((*CreateAppResponse)(nil), "gwappmgr.CreateAppResponse")
	proto.RegisterType((*AppListResponse)(nil), "gwappmgr.AppListResponse")
	proto.RegisterType((*AppDetailResponse)(nil), "gwappmgr.AppDetailResponse")
	proto.RegisterType((*AppID)(nil), "gwappmgr.AppID")
	proto.RegisterType((*UpdateAppRequest)(nil), "gwappmgr.UpdateAppRequest")
	proto.RegisterType((*AppOverviewResponse)(nil), "gwappmgr.AppOverviewResponse")
	proto.RegisterType((*AppLeaderBoardResponse)(nil), "gwappmgr.AppLeaderBoardResponse")
	proto.RegisterType((*AppLeaderBoardDetail)(nil), "gwappmgr.AppLeaderBoardDetail")
	proto.RegisterType((*CreateChartRequest)(nil), "gwappmgr.CreateChartRequest")
	proto.RegisterType((*ChartListRequest)(nil), "gwappmgr.ChartListRequest")
	proto.RegisterType((*ChartListResponse)(nil), "gwappmgr.ChartListResponse")
	proto.RegisterType((*ChartDetailRequest)(nil), "gwappmgr.ChartDetailRequest")
	proto.RegisterType((*ChartDetailResponse)(nil), "gwappmgr.ChartDetailResponse")
	proto.RegisterType((*DeleteChartRequest)(nil), "gwappmgr.DeleteChartRequest")
	proto.RegisterType((*CreateNamespaceRequest)(nil), "gwappmgr.CreateNamespaceRequest")
	proto.RegisterType((*CreateNamespaceResponse)(nil), "gwappmgr.CreateNamespaceResponse")
	proto.RegisterType((*NamespaceListResponse)(nil), "gwappmgr.NamespaceListResponse")
	proto.RegisterType((*UpdateNamespaceRequest)(nil), "gwappmgr.UpdateNamespaceRequest")
	proto.RegisterType((*DeleteNamespaceRequest)(nil), "gwappmgr.DeleteNamespaceRequest")
	proto.RegisterType((*DownloadChartRequest)(nil), "gwappmgr.DownloadChartRequest")
	proto.RegisterType((*DownloadChartResponse)(nil), "gwappmgr.DownloadChartResponse")
	proto.RegisterType((*SaveAsChartRequest)(nil), "gwappmgr.SaveAsChartRequest")
}

func init() { proto.RegisterFile("taskmgr/v1/taskmgr.proto", fileDescriptor_dbc0cfcc64f892be) }

var fileDescriptor_dbc0cfcc64f892be = []byte{
	// 1480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4d, 0x6f, 0x1b, 0x37,
	0x13, 0x86, 0x64, 0x5b, 0xb6, 0x66, 0x25, 0x4b, 0xa2, 0x63, 0x5b, 0x91, 0x9d, 0xc4, 0xde, 0x00,
	0x81, 0xe2, 0x00, 0x16, 0x92, 0x17, 0x08, 0x5e, 0xf4, 0x54, 0x45, 0x6a, 0x01, 0x35, 0x4e, 0x5a,
	0x28, 0x6d, 0xda, 0x14, 0x45, 0x05, 0x5a, 0xcb, 0xc8, 0x8b, 0xee, 0x07, 0xb3, 0x5c, 0xc9, 0xc8,
	0x35, 0x40, 0xaf, 0xbd, 0xf4, 0x0f, 0xf5, 0xd6, 0x63, 0x0b, 0xf4, 0xda, 0x63, 0x7f, 0x48, 0xc1,
	0x21, 0x77, 0xc5, 0x5d, 0xad, 0x9d, 0x9c, 0x82, 0x9e, 0xb4, 0x1a, 0x3e, 0x7c, 0x86, 0x1c, 0x3e,
	0xf3, 0x01, 0xed, 0x98, 0x8a, 0x9f, 0xfc, 0x59, 0xd4, 0x5b, 0x3c, 0xec, 0xe9, 0xcf, 0x53, 0x1e,
	0x85, 0x71, 0x48, 0xb6, 0x66, 0x97, 0x94, 0x73, 0x7f, 0x16, 0x75, 0x0e, 0x67, 0x61, 0x38, 0xf3,
	0x58, 0x8f, 0x72, 0xb7, 0x47, 0x83, 0x20, 0x8c, 0x69, 0xec, 0x86, 0x81, 0x50, 0xb8, 0xce, 0xce,
	0x34, 0xf4, 0xfd, 0x30, 0xe8, 0xa9, 0x1f, 0x65, 0xb4, 0xff, 0x58, 0x83, 0xe6, 0x20, 0x62, 0x34,
	0x66, 0x7d, 0xce, 0xc7, 0xec, 0xcd, 0x9c, 0x89, 0x98, 0x10, 0x58, 0x0f, 0xa8, 0xcf, 0xda, 0xa5,
	0xa3, 0x52, 0xb7, 0x3a, 0xc6, 0x6f, 0x69, 0x8b, 0xdf, 0x72, 0xd6, 0x2e, 0x2b, 0x9b, 0xfc, 0x26,
	0x87, 0x50, 0x9d, 0x5e, 0xd0, 0x28, 0x46, 0xf0, 0x1a, 0x2e, 0x2c, 0x0d, 0xe9, 0x6a, 0xc4, 0x78,
	0xd8, 0x5e, 0x37, 0x56, 0xa5, 0x81, 0xd8, 0x50, 0xc3, 0x3f, 0x0b, 0x16, 0x09, 0x37, 0x0c, 0xda,
	0x1b, 0x08, 0xc8, 0xd8, 0x48, 0x17, 0x1a, 0xf8, 0x9f, 0x72, 0x9e, 0xc0, 0x2a, 0x08, 0xcb, 0x9b,
	0xc9, 0x31, 0xd4, 0xa4, 0x4f, 0xc1, 0xe9, 0x94, 0x4d, 0x5c, 0xa7, 0xbd, 0x89, 0x30, 0x2b, 0xb5,
	0x8d, 0x1c, 0xb2, 0x03, 0x1b, 0x81, 0x90, 0x6b, 0x5b, 0xfa, 0x56, 0x62, 0xe4, 0x90, 0x7d, 0xd8,
	0x0c, 0xc4, 0x04, 0xcf, 0x5f, 0x45, 0x73, 0x25, 0x10, 0xcf, 0xe5, 0xe1, 0x6d, 0xa8, 0x07, 0x62,
	0x32, 0xf5, 0xe6, 0x22, 0x66, 0x91, 0xdc, 0x05, 0x9a, 0x51, 0x0c, 0x94, 0x6d, 0xe4, 0x90, 0x7b,
	0xd0, 0x30, 0x30, 0x48, 0x62, 0x21, 0xaa, 0x9e, 0xa2, 0x90, 0xeb, 0x08, 0x6a, 0x12, 0xc7, 0xe7,
	0x13, 0xcf, 0xf5, 0xdd, 0xb8, 0x5d, 0x3b, 0x2a, 0x75, 0xd7, 0xc7, 0x10, 0x88, 0x01, 0x9f, 0x9f,
	0x49, 0x8b, 0x46, 0xf8, 0xcc, 0xd7, 0x88, 0x7a, 0x82, 0x78, 0xc6, 0x7c, 0x85, 0xe8, 0x42, 0x33,
	0x10, 0x13, 0x11, 0x87, 0x11, 0x9d, 0x31, 0x8d, 0xda, 0x46, 0xd4, 0x76, 0x20, 0x5e, 0x28, 0x33,
	0x22, 0xed, 0x13, 0x68, 0x19, 0x0f, 0x2a, 0x78, 0x18, 0x08, 0x46, 0x76, 0xa1, 0x42, 0x39, 0x97,
	0xf7, 0x50, 0x6f, 0xba, 0x41, 0x39, 0x1f, 0x39, 0xf6, 0x53, 0x68, 0xf4, 0x39, 0x3f, 0x73, 0x45,
	0x9c, 0x22, 0xff, 0x0f, 0x96, 0x44, 0xca, 0x37, 0x8a, 0x62, 0xd1, 0x2e, 0x1d, 0xad, 0x75, 0xad,
	0x47, 0xfb, 0xa7, 0xa6, 0x68, 0x4e, 0x91, 0x59, 0xae, 0x8f, 0x81, 0x26, 0x9f, 0xc2, 0x7e, 0x0a,
	0xad, 0x3e, 0xe7, 0x43, 0x16, 0x53, 0xd7, 0x4b, 0xe9, 0x1e, 0x03, 0x2c, 0xe9, 0xd0, 0xf9, 0x35,
	0x6c, 0xd5, 0x94, 0xcd, 0xbe, 0x0d, 0x1b, 0x7d, 0xce, 0x47, 0xc3, 0xab, 0x4e, 0xfe, 0x7b, 0x09,
	0x9a, 0xdf, 0x70, 0xe7, 0xfd, 0xba, 0x5d, 0xee, 0x2f, 0x1b, 0xfb, 0xff, 0x3b, 0xd2, 0xb5, 0xff,
	0x2e, 0xc1, 0x4e, 0x9f, 0xf3, 0x2f, 0x17, 0x2c, 0x5a, 0xb8, 0xec, 0x32, 0x8d, 0xdc, 0x5d, 0xa8,
	0x27, 0xd2, 0x9a, 0x86, 0xf3, 0x40, 0x05, 0x6f, 0x63, 0x5c, 0xd3, 0xc6, 0x81, 0xb4, 0x91, 0x07,
	0xd0, 0x62, 0xc1, 0xc2, 0x8d, 0xc2, 0xc0, 0x67, 0x41, 0xac, 0x81, 0x65, 0x04, 0x36, 0x8d, 0x05,
	0x05, 0x3e, 0x86, 0x5a, 0xc4, 0x66, 0x6e, 0x18, 0x68, 0xdc, 0x1a, 0xe2, 0x2c, 0x65, 0x53, 0x90,
	0x7b, 0xd0, 0x88, 0xc3, 0x98, 0x7a, 0x13, 0x19, 0x33, 0x85, 0x5a, 0x47, 0x54, 0x1d, 0xcd, 0x7d,
	0xce, 0x15, 0xae, 0x0b, 0xcd, 0x0b, 0x46, 0xbd, 0xf8, 0xc2, 0x00, 0x6e, 0x20, 0x70, 0x5b, 0xd9,
	0x13, 0xa4, 0x7d, 0x06, 0x7b, 0x52, 0x62, 0x8c, 0x3a, 0x2c, 0x7a, 0x12, 0xd2, 0xc8, 0x49, 0x2f,
	0xf8, 0x08, 0xd6, 0x3d, 0x57, 0xc4, 0x5a, 0x62, 0xb7, 0x4f, 0x93, 0x32, 0x76, 0x9a, 0xc5, 0x6b,
	0x41, 0x21, 0xd6, 0x7e, 0x02, 0x37, 0x8a, 0x56, 0x0b, 0x5f, 0x7e, 0x0f, 0x2a, 0xc1, 0xdc, 0x3f,
	0x67, 0x11, 0x06, 0xa4, 0x34, 0xd6, 0xff, 0xec, 0x5f, 0x4a, 0x40, 0x54, 0x86, 0x0c, 0xe4, 0x53,
	0x24, 0xe2, 0xb9, 0x05, 0x80, 0x4f, 0x83, 0x5a, 0xd5, 0x44, 0xea, 0xd1, 0xa5, 0x24, 0xc9, 0x81,
	0x96, 0xc4, 0x64, 0xa1, 0x09, 0xab, 0xe3, 0x2d, 0x34, 0xbc, 0x64, 0xd1, 0x72, 0xef, 0x8a, 0x9c,
	0xb0, 0x00, 0xa4, 0xcb, 0xaf, 0x5d, 0x8f, 0x61, 0x40, 0x6b, 0x7a, 0xf9, 0x73, 0xd7, 0x63, 0xf6,
	0x43, 0x68, 0xe2, 0x49, 0x54, 0x1e, 0x7e, 0xc8, 0x69, 0xec, 0x4f, 0xa1, 0x65, 0x6c, 0xd1, 0x01,
	0x7d, 0x00, 0x15, 0x44, 0x24, 0x59, 0xbb, 0x93, 0xcd, 0x33, 0x75, 0x5b, 0x0d, 0xb1, 0xcf, 0x81,
	0xa0, 0x21, 0xc9, 0x57, 0xe5, 0xf6, 0x3e, 0x6c, 0xe0, 0xba, 0xce, 0xd4, 0x42, 0x06, 0x85, 0x90,
	0x6a, 0x12, 0x17, 0xe1, 0xe5, 0x24, 0x91, 0xb7, 0x8a, 0x89, 0x25, 0x6d, 0x2f, 0xb5, 0xb4, 0x7f,
	0x2b, 0xc1, 0x4e, 0xc6, 0x89, 0x3e, 0xe8, 0x15, 0xfd, 0x05, 0xaf, 0xaa, 0xfb, 0x0b, 0x26, 0xda,
	0x00, 0xb6, 0x35, 0xbb, 0x83, 0x04, 0xa2, 0xbd, 0x86, 0x17, 0x3b, 0xc8, 0x1e, 0x4b, 0xbb, 0xd3,
	0x4e, 0x72, 0x5b, 0xe4, 0xc3, 0x45, 0x8c, 0x3a, 0x3e, 0x9b, 0xf8, 0x8e, 0xce, 0xe5, 0x2d, 0x65,
	0x78, 0xe6, 0x90, 0x3b, 0x60, 0x2d, 0xa8, 0x37, 0x67, 0x62, 0xf2, 0x96, 0xfa, 0x9e, 0xce, 0x64,
	0x50, 0xa6, 0x57, 0xd4, 0xf7, 0xec, 0x10, 0xc8, 0x90, 0x79, 0xec, 0xa3, 0x69, 0xc5, 0x7e, 0x57,
	0x86, 0x3d, 0xa5, 0xce, 0xe7, 0x49, 0xf3, 0x4a, 0xbc, 0x6e, 0x43, 0x39, 0x2d, 0x83, 0x65, 0xd7,
	0x49, 0xc3, 0x58, 0x36, 0xc2, 0x28, 0xd9, 0x97, 0x4d, 0x2b, 0x61, 0x4f, 0x5b, 0xd6, 0x31, 0xd4,
	0x32, 0xfd, 0x4a, 0xc5, 0xc3, 0x9a, 0x1a, 0xdd, 0x4a, 0xd6, 0x1d, 0xe9, 0x5f, 0xd6, 0x09, 0x59,
	0x5f, 0x31, 0x28, 0xeb, 0xe3, 0x5a, 0x62, 0x1c, 0xd2, 0x98, 0xe1, 0x0d, 0xd3, 0x7e, 0x56, 0x41,
	0xc0, 0xd6, 0x34, 0xe9, 0x66, 0x07, 0x50, 0x5d, 0xb6, 0xb2, 0x4d, 0xb5, 0xe8, 0x27, 0x8d, 0xec,
	0x2e, 0xd4, 0xb3, 0x5d, 0x6c, 0x4b, 0xd1, 0x0b, 0xb3, 0x87, 0xdd, 0x87, 0xfd, 0x95, 0x18, 0x68,
	0xed, 0xe4, 0x82, 0x60, 0x4f, 0x61, 0x37, 0x05, 0x65, 0xb2, 0xe1, 0x0b, 0x68, 0x2d, 0x47, 0x82,
	0x6c, 0x3b, 0xbb, 0x95, 0xd5, 0x8f, 0xe1, 0x04, 0xdb, 0x50, 0x33, 0xc8, 0x1a, 0x84, 0x7d, 0x09,
	0x7b, 0xaa, 0xd9, 0xac, 0xbc, 0x49, 0x26, 0x10, 0xa5, 0xeb, 0x02, 0x51, 0x7e, 0x5f, 0x20, 0xd6,
	0x0a, 0x02, 0xd1, 0x85, 0x3d, 0x25, 0xbf, 0xf7, 0x89, 0xc1, 0x7e, 0x03, 0x37, 0x86, 0xe1, 0x65,
	0xe0, 0x85, 0xd4, 0xf9, 0x58, 0x52, 0x7d, 0x0c, 0xbb, 0x39, 0x97, 0x3a, 0xf4, 0xd9, 0x7a, 0x57,
	0xca, 0xd7, 0xbb, 0x3f, 0x4b, 0x40, 0x5e, 0xd0, 0x05, 0xeb, 0x8b, 0x8f, 0x58, 0x80, 0x05, 0x5d,
	0x30, 0x2a, 0x70, 0xb3, 0x6e, 0xe8, 0xca, 0x22, 0x77, 0xdf, 0x01, 0x4b, 0x2f, 0xe3, 0x76, 0x5d,
	0x05, 0x94, 0x09, 0xf7, 0xe7, 0xca, 0x44, 0x05, 0x6f, 0x64, 0x94, 0x89, 0x47, 0x3f, 0xd7, 0xa1,
	0xd2, 0xe7, 0xfc, 0xd9, 0x2c, 0x22, 0x3f, 0x40, 0x35, 0x9d, 0xbf, 0x48, 0x67, 0xd9, 0xd5, 0xf2,
	0x53, 0x76, 0xe7, 0xa0, 0x70, 0x4d, 0x85, 0xd0, 0xde, 0x7b, 0xf7, 0xd7, 0x3f, 0xbf, 0x96, 0x9b,
	0xb6, 0xd5, 0xa3, 0x9c, 0xf7, 0x30, 0xf7, 0xd8, 0x27, 0xa5, 0x13, 0x72, 0x06, 0x9b, 0x7a, 0x62,
	0x23, 0xb9, 0xe2, 0xfc, 0x99, 0xcf, 0xe3, 0xb7, 0x9d, 0x9b, 0xd9, 0x36, 0x6a, 0x24, 0x84, 0xdd,
	0x42, 0x4a, 0x8b, 0x54, 0x91, 0x52, 0xb6, 0x53, 0xf2, 0x1c, 0xaa, 0xe9, 0xc8, 0x46, 0x1a, 0x99,
	0xad, 0xa3, 0xa1, 0x79, 0xc0, 0x95, 0xc1, 0xce, 0xde, 0x41, 0xb6, 0x3a, 0x51, 0x07, 0x54, 0xc5,
	0x96, 0x8c, 0xa0, 0x3a, 0xa0, 0xc1, 0x94, 0xc9, 0x41, 0x61, 0x95, 0xaf, 0xe8, 0xc0, 0xf9, 0x8b,
	0xe2, 0x6e, 0x79, 0xd1, 0x21, 0x6c, 0x7d, 0x35, 0x8f, 0x66, 0xec, 0xc3, 0x99, 0x08, 0x32, 0xd5,
	0x4e, 0x00, 0x99, 0xb8, 0xdc, 0x4c, 0xbe, 0x86, 0x6a, 0x3a, 0x25, 0x9a, 0x8f, 0x91, 0x1f, 0x1d,
	0x3f, 0xe4, 0x6c, 0x73, 0xdc, 0x23, 0xcf, 0xf6, 0x1d, 0x58, 0xc6, 0xc4, 0x56, 0xfc, 0x10, 0xb7,
	0x32, 0x67, 0xce, 0x4f, 0x77, 0xf6, 0x2e, 0x52, 0x37, 0x48, 0x1d, 0xa9, 0xc3, 0x84, 0x8a, 0xc2,
	0x76, 0x76, 0xbe, 0x29, 0x26, 0x3f, 0xba, 0x6a, 0x58, 0x4a, 0xf9, 0xdb, 0xc8, 0x4f, 0x48, 0x53,
	0x3d, 0x36, 0x22, 0xce, 0x91, 0xf0, 0x7b, 0xb0, 0x8c, 0xe9, 0x87, 0x1c, 0xe6, 0x55, 0x68, 0xe6,
	0x64, 0x71, 0x58, 0x34, 0xb7, 0x5d, 0xef, 0x61, 0x86, 0x19, 0xea, 0x7c, 0x05, 0xd5, 0x74, 0x2c,
	0xc9, 0x68, 0x3f, 0x37, 0xde, 0x64, 0xb4, 0x9f, 0x9f, 0x63, 0x0c, 0x69, 0x29, 0x7e, 0x94, 0x2a,
	0x05, 0xcb, 0x18, 0x25, 0x32, 0xc7, 0x5e, 0x19, 0x63, 0xcc, 0xe0, 0x17, 0xcc, 0x1f, 0x46, 0xf0,
	0x95, 0x03, 0xad, 0xde, 0x6f, 0xc1, 0x32, 0x7a, 0xbd, 0xe9, 0x62, 0x75, 0x04, 0x28, 0x8e, 0x8c,
	0x26, 0x3e, 0x59, 0x12, 0xcb, 0x7d, 0x32, 0xe4, 0x46, 0xbd, 0x33, 0x89, 0x57, 0xcb, 0xe0, 0xb5,
	0x21, 0xef, 0x24, 0xc4, 0xaa, 0x36, 0xc9, 0x90, 0xbb, 0x50, 0xcf, 0x14, 0x61, 0x62, 0x0c, 0xd2,
	0x45, 0x0d, 0xa1, 0x73, 0xe7, 0xca, 0x75, 0x1d, 0x9d, 0x7d, 0xf4, 0xd5, 0x22, 0x8d, 0xe4, 0x12,
	0x1a, 0x45, 0x62, 0x68, 0xe4, 0xba, 0x32, 0x39, 0xca, 0xab, 0x27, 0xdf, 0xa7, 0x3a, 0xc7, 0xd7,
	0x20, 0xb4, 0xc3, 0x43, 0x74, 0xb8, 0x67, 0xb7, 0x7a, 0x69, 0xe3, 0x35, 0x34, 0xf5, 0x23, 0xd4,
	0x33, 0x0d, 0xbe, 0x38, 0x23, 0x8c, 0x5b, 0x15, 0x8e, 0x03, 0xc6, 0xad, 0x96, 0x4e, 0x50, 0x58,
	0xaf, 0xa1, 0x91, 0xeb, 0xed, 0xe6, 0xad, 0x8a, 0xdb, 0x7e, 0xf1, 0x23, 0x15, 0xdd, 0x63, 0x59,
	0x34, 0xa6, 0xd0, 0xc8, 0xb5, 0x72, 0xd3, 0x4f, 0x71, 0x97, 0x2f, 0xf6, 0x73, 0x13, 0xfd, 0xec,
	0x9c, 0x98, 0x7e, 0x94, 0xd2, 0xce, 0x2b, 0x88, 0xfb, 0xdf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x1a, 0x1d, 0xf0, 0x53, 0x2e, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppMgrClient is the client API for AppMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppMgrClient interface {
	// Sends request to start a app and list app
	CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error)
	AppList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppListResponse, error)
	AppDetail(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*AppDetailResponse, error)
	CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error)
	UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error)
	AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error)
	AppLeaderBoard(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppLeaderBoardResponse, error)
	CreateChart(ctx context.Context, in *CreateChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error)
	ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error)
	DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	SaveAsChart(ctx context.Context, in *SaveAsChartRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DownloadChart(ctx context.Context, in *DownloadChartRequest, opts ...grpc.CallOption) (*DownloadChartResponse, error)
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	NamespaceList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error)
	UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type appMgrClient struct {
	cc *grpc.ClientConn
}

func NewAppMgrClient(cc *grpc.ClientConn) AppMgrClient {
	return &appMgrClient{cc}
}

func (c *appMgrClient) CreateApp(ctx context.Context, in *CreateAppRequest, opts ...grpc.CallOption) (*CreateAppResponse, error) {
	out := new(CreateAppResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CreateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppDetail(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*AppDetailResponse, error) {
	out := new(AppDetailResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CancelApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CancelApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) PurgeApp(ctx context.Context, in *AppID, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/PurgeApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateApp(ctx context.Context, in *UpdateAppRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/UpdateApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppOverview(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppOverviewResponse, error) {
	out := new(AppOverviewResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppOverview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) AppLeaderBoard(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AppLeaderBoardResponse, error) {
	out := new(AppLeaderBoardResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/AppLeaderBoard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CreateChart(ctx context.Context, in *CreateChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CreateChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartList(ctx context.Context, in *ChartListRequest, opts ...grpc.CallOption) (*ChartListResponse, error) {
	out := new(ChartListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/ChartList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) ChartDetail(ctx context.Context, in *ChartDetailRequest, opts ...grpc.CallOption) (*ChartDetailResponse, error) {
	out := new(ChartDetailResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/ChartDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteChart(ctx context.Context, in *DeleteChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DeleteChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) SaveAsChart(ctx context.Context, in *SaveAsChartRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/SaveAsChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DownloadChart(ctx context.Context, in *DownloadChartRequest, opts ...grpc.CallOption) (*DownloadChartResponse, error) {
	out := new(DownloadChartResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DownloadChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) NamespaceList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*NamespaceListResponse, error) {
	out := new(NamespaceListResponse)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/NamespaceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) UpdateNamespace(ctx context.Context, in *UpdateNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/UpdateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appMgrClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, "/gwappmgr.AppMgr/DeleteNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMgrServer is the server API for AppMgr service.
type AppMgrServer interface {
	// Sends request to start a app and list app
	CreateApp(context.Context, *CreateAppRequest) (*CreateAppResponse, error)
	AppList(context.Context, *common.Empty) (*AppListResponse, error)
	AppDetail(context.Context, *AppID) (*AppDetailResponse, error)
	CancelApp(context.Context, *AppID) (*common.Empty, error)
	PurgeApp(context.Context, *AppID) (*common.Empty, error)
	UpdateApp(context.Context, *UpdateAppRequest) (*common.Empty, error)
	AppOverview(context.Context, *common.Empty) (*AppOverviewResponse, error)
	AppLeaderBoard(context.Context, *common.Empty) (*AppLeaderBoardResponse, error)
	CreateChart(context.Context, *CreateChartRequest) (*common.Empty, error)
	ChartList(context.Context, *ChartListRequest) (*ChartListResponse, error)
	ChartDetail(context.Context, *ChartDetailRequest) (*ChartDetailResponse, error)
	DeleteChart(context.Context, *DeleteChartRequest) (*common.Empty, error)
	SaveAsChart(context.Context, *SaveAsChartRequest) (*common.Empty, error)
	DownloadChart(context.Context, *DownloadChartRequest) (*DownloadChartResponse, error)
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	NamespaceList(context.Context, *common.Empty) (*NamespaceListResponse, error)
	UpdateNamespace(context.Context, *UpdateNamespaceRequest) (*common.Empty, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*common.Empty, error)
}

// UnimplementedAppMgrServer can be embedded to have forward compatible implementations.
type UnimplementedAppMgrServer struct {
}

func (*UnimplementedAppMgrServer) CreateApp(ctx context.Context, req *CreateAppRequest) (*CreateAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppList(ctx context.Context, req *common.Empty) (*AppListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppList not implemented")
}
func (*UnimplementedAppMgrServer) AppDetail(ctx context.Context, req *AppID) (*AppDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppDetail not implemented")
}
func (*UnimplementedAppMgrServer) CancelApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelApp not implemented")
}
func (*UnimplementedAppMgrServer) PurgeApp(ctx context.Context, req *AppID) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeApp not implemented")
}
func (*UnimplementedAppMgrServer) UpdateApp(ctx context.Context, req *UpdateAppRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApp not implemented")
}
func (*UnimplementedAppMgrServer) AppOverview(ctx context.Context, req *common.Empty) (*AppOverviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppOverview not implemented")
}
func (*UnimplementedAppMgrServer) AppLeaderBoard(ctx context.Context, req *common.Empty) (*AppLeaderBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppLeaderBoard not implemented")
}
func (*UnimplementedAppMgrServer) CreateChart(ctx context.Context, req *CreateChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChart not implemented")
}
func (*UnimplementedAppMgrServer) ChartList(ctx context.Context, req *ChartListRequest) (*ChartListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartList not implemented")
}
func (*UnimplementedAppMgrServer) ChartDetail(ctx context.Context, req *ChartDetailRequest) (*ChartDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChartDetail not implemented")
}
func (*UnimplementedAppMgrServer) DeleteChart(ctx context.Context, req *DeleteChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChart not implemented")
}
func (*UnimplementedAppMgrServer) SaveAsChart(ctx context.Context, req *SaveAsChartRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveAsChart not implemented")
}
func (*UnimplementedAppMgrServer) DownloadChart(ctx context.Context, req *DownloadChartRequest) (*DownloadChartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadChart not implemented")
}
func (*UnimplementedAppMgrServer) CreateNamespace(ctx context.Context, req *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) NamespaceList(ctx context.Context, req *common.Empty) (*NamespaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NamespaceList not implemented")
}
func (*UnimplementedAppMgrServer) UpdateNamespace(ctx context.Context, req *UpdateNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNamespace not implemented")
}
func (*UnimplementedAppMgrServer) DeleteNamespace(ctx context.Context, req *DeleteNamespaceRequest) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}

func RegisterAppMgrServer(s *grpc.Server, srv AppMgrServer) {
	s.RegisterService(&_AppMgr_serviceDesc, srv)
}

func _AppMgr_CreateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CreateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateApp(ctx, req.(*CreateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppDetail(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CancelApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CancelApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CancelApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CancelApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_PurgeApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).PurgeApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/PurgeApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).PurgeApp(ctx, req.(*AppID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/UpdateApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateApp(ctx, req.(*UpdateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppOverview(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_AppLeaderBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).AppLeaderBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/AppLeaderBoard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).AppLeaderBoard(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CreateChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CreateChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateChart(ctx, req.(*CreateChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/ChartList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartList(ctx, req.(*ChartListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_ChartDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChartDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).ChartDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/ChartDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).ChartDetail(ctx, req.(*ChartDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DeleteChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteChart(ctx, req.(*DeleteChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_SaveAsChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAsChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).SaveAsChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/SaveAsChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).SaveAsChart(ctx, req.(*SaveAsChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DownloadChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadChartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DownloadChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DownloadChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DownloadChart(ctx, req.(*DownloadChartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_NamespaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).NamespaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/NamespaceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).NamespaceList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_UpdateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).UpdateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/UpdateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).UpdateNamespace(ctx, req.(*UpdateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppMgr_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMgrServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gwappmgr.AppMgr/DeleteNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMgrServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gwappmgr.AppMgr",
	HandlerType: (*AppMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateApp",
			Handler:    _AppMgr_CreateApp_Handler,
		},
		{
			MethodName: "AppList",
			Handler:    _AppMgr_AppList_Handler,
		},
		{
			MethodName: "AppDetail",
			Handler:    _AppMgr_AppDetail_Handler,
		},
		{
			MethodName: "CancelApp",
			Handler:    _AppMgr_CancelApp_Handler,
		},
		{
			MethodName: "PurgeApp",
			Handler:    _AppMgr_PurgeApp_Handler,
		},
		{
			MethodName: "UpdateApp",
			Handler:    _AppMgr_UpdateApp_Handler,
		},
		{
			MethodName: "AppOverview",
			Handler:    _AppMgr_AppOverview_Handler,
		},
		{
			MethodName: "AppLeaderBoard",
			Handler:    _AppMgr_AppLeaderBoard_Handler,
		},
		{
			MethodName: "CreateChart",
			Handler:    _AppMgr_CreateChart_Handler,
		},
		{
			MethodName: "ChartList",
			Handler:    _AppMgr_ChartList_Handler,
		},
		{
			MethodName: "ChartDetail",
			Handler:    _AppMgr_ChartDetail_Handler,
		},
		{
			MethodName: "DeleteChart",
			Handler:    _AppMgr_DeleteChart_Handler,
		},
		{
			MethodName: "SaveAsChart",
			Handler:    _AppMgr_SaveAsChart_Handler,
		},
		{
			MethodName: "DownloadChart",
			Handler:    _AppMgr_DownloadChart_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _AppMgr_CreateNamespace_Handler,
		},
		{
			MethodName: "NamespaceList",
			Handler:    _AppMgr_NamespaceList_Handler,
		},
		{
			MethodName: "UpdateNamespace",
			Handler:    _AppMgr_UpdateNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _AppMgr_DeleteNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "taskmgr/v1/taskmgr.proto",
}
